# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ConversationsV1UserConversationApi
  class ConversationsV1UserConversationApi < BaseApi
    # Update a specific User Conversation.
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the Conversation resource is associated with.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [String] conversation_sid Required parameter: The unique SID
    # identifier of the Conversation. This value can be either the `sid` or the
    # `unique_name` of the [Conversation
    # resource](https://www.twilio.com/docs/conversations/api/conversation-resou
    # rce).
    # @param [ServiceUserConversationNotificationLevel] notification_level
    # Optional parameter: The Notification Level of this User Conversation. One
    # of `default` or `muted`.
    # @param [DateTime] last_read_timestamp Optional parameter: The date of the
    # last message read in conversation by the user, given in ISO 8601 format.
    # @param [Integer] last_read_message_index Optional parameter: The index of
    # the last Message in the Conversation that the Participant has read.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_service_user_conversation(chat_service_sid,
                                         user_sid,
                                         conversation_sid,
                                         notification_level: nil,
                                         last_read_timestamp: nil,
                                         last_read_message_index: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations/{ConversationSid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(conversation_sid, key: 'ConversationSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .form_param(new_parameter(notification_level, key: 'NotificationLevel'))
                   .form_param(new_parameter(last_read_timestamp, key: 'LastReadTimestamp'))
                   .form_param(new_parameter(last_read_message_index, key: 'LastReadMessageIndex'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ServiceUserConversation.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Delete a specific User Conversation.
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the Conversation resource is associated with.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [String] conversation_sid Required parameter: The unique SID
    # identifier of the Conversation. This value can be either the `sid` or the
    # `unique_name` of the [Conversation
    # resource](https://www.twilio.com/docs/conversations/api/conversation-resou
    # rce).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_service_user_conversation(chat_service_sid,
                                         user_sid,
                                         conversation_sid)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations/{ConversationSid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(conversation_sid, key: 'ConversationSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true))
        .execute
    end

    # Fetch a specific User Conversation.
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the Conversation resource is associated with.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [String] conversation_sid Required parameter: The unique SID
    # identifier of the Conversation. This value can be either the `sid` or the
    # `unique_name` of the [Conversation
    # resource](https://www.twilio.com/docs/conversations/api/conversation-resou
    # rce).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def fetch_service_user_conversation(chat_service_sid,
                                        user_sid,
                                        conversation_sid)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations/{ConversationSid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(conversation_sid, key: 'ConversationSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ServiceUserConversation.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Retrieve a list of all User Conversations for the User.
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the Conversation resource is associated with.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [Integer] page_size Optional parameter: How many resources to
    # return in each list page. The default is 50, and the maximum is 50.
    # @param [Integer] page Optional parameter: The page index. This value is
    # simply for client state.
    # @param [String] page_token Optional parameter: The page token. This is
    # provided by the API.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_service_user_conversation(chat_service_sid,
                                       user_sid,
                                       page_size: nil,
                                       page: nil,
                                       page_token: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Services/{ChatServiceSid}/Users/{UserSid}/Conversations',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page_size, key: 'PageSize'))
                   .query_param(new_parameter(page, key: 'Page'))
                   .query_param(new_parameter(page_token, key: 'PageToken'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ListServiceUserConversationResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Update a specific User Conversation.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [String] conversation_sid Required parameter: The unique SID
    # identifier of the Conversation. This value can be either the `sid` or the
    # `unique_name` of the [Conversation
    # resource](https://www.twilio.com/docs/conversations/api/conversation-resou
    # rce).
    # @param [UserConversationNotificationLevel] notification_level Optional
    # parameter: The Notification Level of this User Conversation. One of
    # `default` or `muted`.
    # @param [DateTime] last_read_timestamp Optional parameter: The date of the
    # last message read in conversation by the user, given in ISO 8601 format.
    # @param [Integer] last_read_message_index Optional parameter: The index of
    # the last Message in the Conversation that the Participant has read.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_user_conversation(user_sid,
                                 conversation_sid,
                                 notification_level: nil,
                                 last_read_timestamp: nil,
                                 last_read_message_index: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Users/{UserSid}/Conversations/{ConversationSid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(conversation_sid, key: 'ConversationSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .form_param(new_parameter(notification_level, key: 'NotificationLevel'))
                   .form_param(new_parameter(last_read_timestamp, key: 'LastReadTimestamp'))
                   .form_param(new_parameter(last_read_message_index, key: 'LastReadMessageIndex'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserConversation.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Delete a specific User Conversation.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [String] conversation_sid Required parameter: The unique SID
    # identifier of the Conversation. This value can be either the `sid` or the
    # `unique_name` of the [Conversation
    # resource](https://www.twilio.com/docs/conversations/api/conversation-resou
    # rce).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_user_conversation(user_sid,
                                 conversation_sid)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/v1/Users/{UserSid}/Conversations/{ConversationSid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(conversation_sid, key: 'ConversationSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true))
        .execute
    end

    # Fetch a specific User Conversation.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [String] conversation_sid Required parameter: The unique SID
    # identifier of the Conversation. This value can be either the `sid` or the
    # `unique_name` of the [Conversation
    # resource](https://www.twilio.com/docs/conversations/api/conversation-resou
    # rce).
    # @return [ApiResponse] Complete http response with raw body and status code.
    def fetch_user_conversation(user_sid,
                                conversation_sid)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Users/{UserSid}/Conversations/{ConversationSid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(conversation_sid, key: 'ConversationSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(UserConversation.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Retrieve a list of all User Conversations for the User.
    # @param [String] user_sid Required parameter: The unique SID identifier of
    # the [User
    # resource](https://www.twilio.com/docs/conversations/api/user-resource).
    # This value can be either the `sid` or the `identity` of the User
    # resource.
    # @param [Integer] page_size Optional parameter: How many resources to
    # return in each list page. The default is 50, and the maximum is 50.
    # @param [Integer] page Optional parameter: The page index. This value is
    # simply for client state.
    # @param [String] page_token Optional parameter: The page token. This is
    # provided by the API.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_user_conversation(user_sid,
                               page_size: nil,
                               page: nil,
                               page_token: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Users/{UserSid}/Conversations',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(user_sid, key: 'UserSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page_size, key: 'PageSize'))
                   .query_param(new_parameter(page, key: 'Page'))
                   .query_param(new_parameter(page_token, key: 'PageToken'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ListUserConversationResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end
  end
end
