# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ConversationsV1UserApi
  class ConversationsV1UserApi < BaseApi
    # Add a new conversation user to your service
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the User resource is associated with.
    # @param [String] identity Required parameter: The application-defined
    # string that uniquely identifies the resource's User within the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource).
    # This value is often a username or an email address, and is
    # case-sensitive.
    # @param [ChannelWebhookEnabledType] x_twilio_webhook_enabled Optional
    # parameter: The X-Twilio-Webhook-Enabled HTTP request header
    # @param [String] friendly_name Optional parameter: The string that you
    # assigned to describe the resource.
    # @param [String] attributes Optional parameter: The JSON Object string that
    # stores application-specific data. If attributes have not been set, `{}` is
    # returned.
    # @param [String] role_sid Optional parameter: The SID of a service-level
    # [Role](https://www.twilio.com/docs/conversations/api/role-resource) to
    # assign to the user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_service_user(chat_service_sid,
                            identity,
                            x_twilio_webhook_enabled: nil,
                            friendly_name: nil,
                            attributes: nil,
                            role_sid: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Services/{ChatServiceSid}/Users',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .form_param(new_parameter(identity, key: 'Identity')
                                .is_required(true))
                   .header_param(new_parameter(x_twilio_webhook_enabled, key: 'X-Twilio-Webhook-Enabled'))
                   .form_param(new_parameter(friendly_name, key: 'FriendlyName'))
                   .form_param(new_parameter(attributes, key: 'Attributes'))
                   .form_param(new_parameter(role_sid, key: 'RoleSid'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ServiceUser.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Retrieve a list of all conversation users in your service
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # to read the User resources from.
    # @param [Integer] page_size Optional parameter: How many resources to
    # return in each list page. The default is 50, and the maximum is 50.
    # @param [Integer] page Optional parameter: The page index. This value is
    # simply for client state.
    # @param [String] page_token Optional parameter: The page token. This is
    # provided by the API.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_service_user(chat_service_sid,
                          page_size: nil,
                          page: nil,
                          page_token: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Services/{ChatServiceSid}/Users',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .query_param(new_parameter(page_size, key: 'PageSize'))
                   .query_param(new_parameter(page, key: 'Page'))
                   .query_param(new_parameter(page_token, key: 'PageToken'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ListServiceUserResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Update an existing conversation user in your service
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the User resource is associated with.
    # @param [String] sid Required parameter: The SID of the User resource to
    # update. This value can be either the `sid` or the `identity` of the User
    # resource to update.
    # @param [ChannelWebhookEnabledType] x_twilio_webhook_enabled Optional
    # parameter: The X-Twilio-Webhook-Enabled HTTP request header
    # @param [String] friendly_name Optional parameter: The string that you
    # assigned to describe the resource.
    # @param [String] attributes Optional parameter: The JSON Object string that
    # stores application-specific data. If attributes have not been set, `{}` is
    # returned.
    # @param [String] role_sid Optional parameter: The SID of a service-level
    # [Role](https://www.twilio.com/docs/conversations/api/role-resource) to
    # assign to the user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_service_user(chat_service_sid,
                            sid,
                            x_twilio_webhook_enabled: nil,
                            friendly_name: nil,
                            attributes: nil,
                            role_sid: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Services/{ChatServiceSid}/Users/{Sid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(sid, key: 'Sid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(x_twilio_webhook_enabled, key: 'X-Twilio-Webhook-Enabled'))
                   .form_param(new_parameter(friendly_name, key: 'FriendlyName'))
                   .form_param(new_parameter(attributes, key: 'Attributes'))
                   .form_param(new_parameter(role_sid, key: 'RoleSid'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ServiceUser.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Remove a conversation user from your service
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # to delete the User resource from.
    # @param [String] sid Required parameter: The SID of the User resource to
    # delete. This value can be either the `sid` or the `identity` of the User
    # resource to delete.
    # @param [ChannelWebhookEnabledType] x_twilio_webhook_enabled Optional
    # parameter: The X-Twilio-Webhook-Enabled HTTP request header
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_service_user(chat_service_sid,
                            sid,
                            x_twilio_webhook_enabled: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/v1/Services/{ChatServiceSid}/Users/{Sid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(sid, key: 'Sid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(x_twilio_webhook_enabled, key: 'X-Twilio-Webhook-Enabled'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true))
        .execute
    end

    # Fetch a conversation user from your service
    # @param [String] chat_service_sid Required parameter: The SID of the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # to fetch the User resource from.
    # @param [String] sid Required parameter: The SID of the User resource to
    # fetch. This value can be either the `sid` or the `identity` of the User
    # resource to fetch.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def fetch_service_user(chat_service_sid,
                           sid)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Services/{ChatServiceSid}/Users/{Sid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(chat_service_sid, key: 'ChatServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .template_param(new_parameter(sid, key: 'Sid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ServiceUser.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Add a new conversation user to your account's default service
    # @param [String] identity Required parameter: The application-defined
    # string that uniquely identifies the resource's User within the
    # [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource).
    # This value is often a username or an email address, and is
    # case-sensitive.
    # @param [ChannelWebhookEnabledType] x_twilio_webhook_enabled Optional
    # parameter: The X-Twilio-Webhook-Enabled HTTP request header
    # @param [String] friendly_name Optional parameter: The string that you
    # assigned to describe the resource.
    # @param [String] attributes Optional parameter: The JSON Object string that
    # stores application-specific data. If attributes have not been set, `{}` is
    # returned.
    # @param [String] role_sid Optional parameter: The SID of a service-level
    # [Role](https://www.twilio.com/docs/conversations/api/role-resource) to
    # assign to the user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_user(identity,
                    x_twilio_webhook_enabled: nil,
                    friendly_name: nil,
                    attributes: nil,
                    role_sid: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Users',
                                     Server::DEFAULT2)
                   .form_param(new_parameter(identity, key: 'Identity')
                                .is_required(true))
                   .header_param(new_parameter(x_twilio_webhook_enabled, key: 'X-Twilio-Webhook-Enabled'))
                   .form_param(new_parameter(friendly_name, key: 'FriendlyName'))
                   .form_param(new_parameter(attributes, key: 'Attributes'))
                   .form_param(new_parameter(role_sid, key: 'RoleSid'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(User.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Retrieve a list of all conversation users in your account's default
    # service
    # @param [Integer] page_size Optional parameter: How many resources to
    # return in each list page. The default is 50, and the maximum is 50.
    # @param [Integer] page Optional parameter: The page index. This value is
    # simply for client state.
    # @param [String] page_token Optional parameter: The page token. This is
    # provided by the API.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def list_user(page_size: nil,
                  page: nil,
                  page_token: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Users',
                                     Server::DEFAULT2)
                   .query_param(new_parameter(page_size, key: 'PageSize'))
                   .query_param(new_parameter(page, key: 'Page'))
                   .query_param(new_parameter(page_token, key: 'PageToken'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(ListUserResponse.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Update an existing conversation user in your account's default service
    # @param [String] sid Required parameter: The SID of the User resource to
    # update. This value can be either the `sid` or the `identity` of the User
    # resource to update.
    # @param [ChannelWebhookEnabledType] x_twilio_webhook_enabled Optional
    # parameter: The X-Twilio-Webhook-Enabled HTTP request header
    # @param [String] friendly_name Optional parameter: The string that you
    # assigned to describe the resource.
    # @param [String] attributes Optional parameter: The JSON Object string that
    # stores application-specific data. If attributes have not been set, `{}` is
    # returned.
    # @param [String] role_sid Optional parameter: The SID of a service-level
    # [Role](https://www.twilio.com/docs/conversations/api/role-resource) to
    # assign to the user.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def update_user(sid,
                    x_twilio_webhook_enabled: nil,
                    friendly_name: nil,
                    attributes: nil,
                    role_sid: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Users/{Sid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(sid, key: 'Sid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(x_twilio_webhook_enabled, key: 'X-Twilio-Webhook-Enabled'))
                   .form_param(new_parameter(friendly_name, key: 'FriendlyName'))
                   .form_param(new_parameter(attributes, key: 'Attributes'))
                   .form_param(new_parameter(role_sid, key: 'RoleSid'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(User.method(:from_hash))
                    .is_api_response(true))
        .execute
    end

    # Remove a conversation user from your account's default service
    # @param [String] sid Required parameter: The SID of the User resource to
    # delete. This value can be either the `sid` or the `identity` of the User
    # resource to delete.
    # @param [ChannelWebhookEnabledType] x_twilio_webhook_enabled Optional
    # parameter: The X-Twilio-Webhook-Enabled HTTP request header
    # @return [ApiResponse] Complete http response with raw body and status code.
    def delete_user(sid,
                    x_twilio_webhook_enabled: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::DELETE,
                                     '/v1/Users/{Sid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(sid, key: 'Sid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter(x_twilio_webhook_enabled, key: 'X-Twilio-Webhook-Enabled'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .is_response_void(true)
                    .is_api_response(true))
        .execute
    end

    # Fetch a conversation user from your account's default service
    # @param [String] sid Required parameter: The SID of the User resource to
    # fetch. This value can be either the `sid` or the `identity` of the User
    # resource to fetch.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def fetch_user(sid)
      @api_call
        .request(new_request_builder(HttpMethodEnum::GET,
                                     '/v1/Users/{Sid}',
                                     Server::DEFAULT2)
                   .template_param(new_parameter(sid, key: 'Sid')
                                    .is_required(true)
                                    .should_encode(true))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(User.method(:from_hash))
                    .is_api_response(true))
        .execute
    end
  end
end
