# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # NotifyV1NotificationApi
  class NotifyV1NotificationApi < BaseApi
    # TODO: type endpoint description here
    # @param [String] service_sid Required parameter: The SID of the
    # [Service](https://www.twilio.com/docs/notify/api/service-resource) to
    # create the resource under.
    # @param [String] body Optional parameter: The notification text. For FCM
    # and GCM, translates to `data.twi_body`. For APNS, translates to
    # `aps.alert.body`. For SMS, translates to `body`. SMS requires either this
    # `body` value, or `media_urls` attribute defined in the `sms` parameter of
    # the notification.
    # @param [NotifPriority] priority Optional parameter: The priority of the
    # notification. Can be: `low` or `high` and the default is `high`. A value
    # of `low` optimizes the client app's battery consumption; however,
    # notifications may be delivered with unspecified delay. For FCM and GCM,
    # `low` priority is the same as `Normal` priority. For APNS `low` priority
    # is the same as `5`. A value of `high` sends the notification immediately,
    # and can wake up a sleeping device. For FCM and GCM, `high` is the same as
    # `High` priority. For APNS, `high` is a priority `10`. SMS does not support
    # this property.
    # @param [Integer] ttl Optional parameter: How long, in seconds, the
    # notification is valid. Can be an integer between 0 and 2,419,200, which is
    # 4 weeks, the default and the maximum supported time to live (TTL).
    # Delivery should be attempted if the device is offline until the TTL
    # elapses. Zero means that the notification delivery is attempted
    # immediately, only once, and is not stored for future delivery. SMS does
    # not support this property.
    # @param [String] title Optional parameter: The notification title. For FCM
    # and GCM, this translates to the `data.twi_title` value. For APNS, this
    # translates to the `aps.alert.title` value. SMS does not support this
    # property. This field is not visible on iOS phones and tablets but appears
    # on Apple Watch and Android devices.
    # @param [String] sound Optional parameter: The name of the sound to be
    # played for the notification. For FCM and GCM, this Translates to
    # `data.twi_sound`.  For APNS, this translates to `aps.sound`.  SMS does not
    # support this property.
    # @param [String] action Optional parameter: The actions to display for the
    # notification. For APNS, translates to the `aps.category` value. For GCM,
    # translates to the `data.twi_action` value. For SMS, this parameter is not
    # supported and is omitted from deliveries to those channels.
    # @param [Object] data Optional parameter: The custom key-value pairs of the
    # notification's payload. For FCM and GCM, this value translates to `data`
    # in the FCM and GCM payloads. FCM and GCM [reserve certain
    # keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref)
    # that cannot be used in those channels. For APNS, attributes of `data` are
    # inserted into the APNS payload as custom properties outside of the `aps`
    # dictionary. In all channels, we reserve keys that start with `twi_` for
    # future use. Custom keys that start with `twi_` are not allowed and are
    # rejected as 400 Bad request with no delivery attempted. For SMS, this
    # parameter is not supported and is omitted from deliveries to those
    # channels.
    # @param [Object] apn Optional parameter: The APNS-specific payload that
    # overrides corresponding attributes in the generic payload for APNS
    # Bindings. This property maps to the APNS `Payload` item, therefore the
    # `aps` key must be used to change standard attributes. Adds custom
    # key-value pairs to the root of the dictionary. See the [APNS
    # documentation](https://developer.apple.com/library/content/documentation/N
    # etworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.h
    # tml) for more details. We reserve keys that start with `twi_` for future
    # use. Custom keys that start with `twi_` are not allowed.
    # @param [Object] gcm Optional parameter: The GCM-specific payload that
    # overrides corresponding attributes in the generic payload for GCM
    # Bindings.  This property maps to the root JSON dictionary. See the [GCM
    # documentation](https://firebase.google.com/docs/cloud-messaging/http-serve
    # r-ref) for more details. Target parameters `to`, `registration_ids`, and
    # `notification_key` are not allowed. We reserve keys that start with `twi_`
    # for future use. Custom keys that start with `twi_` are not allowed. GCM
    # also [reserves certain
    # keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref).
    # @param [Object] sms Optional parameter: The SMS-specific payload that
    # overrides corresponding attributes in the generic payload for SMS
    # Bindings.  Each attribute in this value maps to the corresponding `form`
    # parameter of the Twilio
    # [Message](https://www.twilio.com/docs/sms/quickstart) resource.  These
    # parameters of the Message resource are supported in snake case format:
    # `body`, `media_urls`, `status_callback`, and `max_price`.  The
    # `status_callback` parameter overrides the corresponding parameter in the
    # messaging service, if configured. The `media_urls` property expects a JSON
    # array.
    # @param [Object] facebook_messenger Optional parameter: Deprecated.
    # @param [Object] fcm Optional parameter: The FCM-specific payload that
    # overrides corresponding attributes in the generic payload for FCM
    # Bindings. This property maps to the root JSON dictionary. See the [FCM
    # documentation](https://firebase.google.com/docs/cloud-messaging/http-serve
    # r-ref#downstream) for more details. Target parameters `to`,
    # `registration_ids`, `condition`, and `notification_key` are not allowed in
    # this parameter. We reserve keys that start with `twi_` for future use.
    # Custom keys that start with `twi_` are not allowed. FCM also [reserves
    # certain
    # keys](https://firebase.google.com/docs/cloud-messaging/http-server-ref),
    # which cannot be used in that channel.
    # @param [Array[String]] segment Optional parameter: The Segment resource is
    # deprecated. Use the `tag` parameter, instead.
    # @param [Object] alexa Optional parameter: Deprecated.
    # @param [Array[String]] to_binding Optional parameter: The destination
    # address specified as a JSON string.  Multiple `to_binding` parameters can
    # be included but the total size of the request entity should not exceed
    # 1MB. This is typically sufficient for 10,000 phone numbers.
    # @param [String] delivery_callback_url Optional parameter: URL to send
    # webhooks.
    # @param [Array[String]] identity Optional parameter: The `identity` value
    # that uniquely identifies the new resource's
    # [User](https://www.twilio.com/docs/chat/rest/user-resource) within the
    # [Service](https://www.twilio.com/docs/notify/api/service-resource).
    # Delivery will be attempted only to Bindings with an Identity in this list.
    # No more than 20 items are allowed in this list.
    # @param [Array[String]] tag Optional parameter: A tag that selects the
    # Bindings to notify. Repeat this parameter to specify more than one tag, up
    # to a total of 5 tags. The implicit tag `all` is available to notify all
    # Bindings in a Service instance. Similarly, the implicit tags `apn`, `fcm`,
    # `gcm`, `sms` and `facebook-messenger` are available to notify all Bindings
    # in a specific channel.
    # @return [ApiResponse] Complete http response with raw body and status code.
    def create_notification(service_sid,
                            body: nil,
                            priority: nil,
                            ttl: nil,
                            title: nil,
                            sound: nil,
                            action: nil,
                            data: nil,
                            apn: nil,
                            gcm: nil,
                            sms: nil,
                            facebook_messenger: nil,
                            fcm: nil,
                            segment: nil,
                            alexa: nil,
                            to_binding: nil,
                            delivery_callback_url: nil,
                            identity: nil,
                            tag: nil)
      @api_call
        .request(new_request_builder(HttpMethodEnum::POST,
                                     '/v1/Services/{ServiceSid}/Notifications',
                                     Server::DEFAULT3)
                   .template_param(new_parameter(service_sid, key: 'ServiceSid')
                                    .is_required(true)
                                    .should_encode(true))
                   .form_param(new_parameter(body, key: 'Body'))
                   .form_param(new_parameter(priority, key: 'Priority'))
                   .form_param(new_parameter(ttl, key: 'Ttl'))
                   .form_param(new_parameter(title, key: 'Title'))
                   .form_param(new_parameter(sound, key: 'Sound'))
                   .form_param(new_parameter(action, key: 'Action'))
                   .form_param(new_parameter(data, key: 'Data'))
                   .form_param(new_parameter(apn, key: 'Apn'))
                   .form_param(new_parameter(gcm, key: 'Gcm'))
                   .form_param(new_parameter(sms, key: 'Sms'))
                   .form_param(new_parameter(facebook_messenger, key: 'FacebookMessenger'))
                   .form_param(new_parameter(fcm, key: 'Fcm'))
                   .form_param(new_parameter(segment, key: 'Segment'))
                   .form_param(new_parameter(alexa, key: 'Alexa'))
                   .form_param(new_parameter(to_binding, key: 'ToBinding'))
                   .form_param(new_parameter(delivery_callback_url, key: 'DeliveryCallbackUrl'))
                   .form_param(new_parameter(identity, key: 'Identity'))
                   .form_param(new_parameter(tag, key: 'Tag'))
                   .header_param(new_parameter('application/x-www-form-urlencoded', key: 'content-type'))
                   .header_param(new_parameter('application/json', key: 'accept'))
                   .auth(Single.new('accountSid_authToken')))
        .response(new_response_handler
                    .deserializer(APIHelper.method(:custom_type_deserializer))
                    .deserialize_into(Notification.method(:from_hash))
                    .is_api_response(true))
        .execute
    end
  end
end
