# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # Challenge Model.
  class Challenge < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A 34 character string that uniquely identifies this Challenge.
    # @return [String]
    attr_accessor :sid

    # The unique SID identifier of the Account.
    # @return [String]
    attr_accessor :account_sid

    # The unique SID identifier of the Service.
    # @return [String]
    attr_accessor :service_sid

    # The unique SID identifier of the Entity.
    # @return [String]
    attr_accessor :entity_sid

    # Customer unique identity for the Entity owner of the Challenge. This
    # identifier should be immutable, not PII, length between 8 and 64
    # characters, and generated by your external system, such as your user's
    # UUID, GUID, or SID. It can only contain dash (-) separated alphanumeric
    # characters.
    # @return [String]
    attr_accessor :identity

    # The unique SID identifier of the Factor.
    # @return [String]
    attr_accessor :factor_sid

    # The date that this Challenge was created, given in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date that this Challenge was updated, given in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # The date that this Challenge was responded, given in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_responded

    # The date-time when this Challenge expires, given in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format. The default value is
    # five (5) minutes after Challenge creation. The max value is sixty (60)
    # minutes after creation.
    # @return [DateTime]
    attr_accessor :expiration_date

    # The Status of this Challenge. One of `pending`, `expired`, `approved` or
    # `denied`.
    # @return [ChallengeEnumChallengeStatuses]
    attr_accessor :status

    # Reason for the Challenge to be in certain `status`. One of `none`,
    # `not_needed` or `not_requested`.
    # @return [ChallengeEnumChallengeReasons]
    attr_accessor :responded_reason

    # Details provided to give context about the Challenge. Intended to be shown
    # to the end user.
    # @return [Object]
    attr_accessor :details

    # Details provided to give context about the Challenge. Intended to be
    # hidden from the end user. It must be a stringified JSON with only strings
    # values eg. `{"ip": "172.168.1.234"}`
    # @return [Object]
    attr_accessor :hidden_details

    # Custom metadata associated with the challenge. This is added by the
    # Device/SDK directly to allow for the inclusion of device information. It
    # must be a stringified JSON with only strings values eg. `{"os":
    # "Android"}`. Can be up to 1024 characters in length.
    # @return [Object]
    attr_accessor :metadata

    # The Factor Type of this Challenge. Currently `push` and `totp` are
    # supported.
    # @return [ChallengeEnumFactorTypes]
    attr_accessor :factor_type

    # The URL of this resource.
    # @return [String]
    attr_accessor :url

    # Contains a dictionary of URL links to nested resources of this Challenge.
    # @return [Object]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sid'] = 'sid'
      @_hash['account_sid'] = 'account_sid'
      @_hash['service_sid'] = 'service_sid'
      @_hash['entity_sid'] = 'entity_sid'
      @_hash['identity'] = 'identity'
      @_hash['factor_sid'] = 'factor_sid'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['date_responded'] = 'date_responded'
      @_hash['expiration_date'] = 'expiration_date'
      @_hash['status'] = 'status'
      @_hash['responded_reason'] = 'responded_reason'
      @_hash['details'] = 'details'
      @_hash['hidden_details'] = 'hidden_details'
      @_hash['metadata'] = 'metadata'
      @_hash['factor_type'] = 'factor_type'
      @_hash['url'] = 'url'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sid
        account_sid
        service_sid
        entity_sid
        identity
        factor_sid
        date_created
        date_updated
        date_responded
        expiration_date
        status
        responded_reason
        details
        hidden_details
        metadata
        factor_type
        url
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        sid
        account_sid
        service_sid
        entity_sid
        identity
        factor_sid
        date_created
        date_updated
        date_responded
        expiration_date
        details
        hidden_details
        metadata
        url
        links
      ]
    end

    def initialize(sid: SKIP, account_sid: SKIP, service_sid: SKIP,
                   entity_sid: SKIP, identity: SKIP, factor_sid: SKIP,
                   date_created: SKIP, date_updated: SKIP, date_responded: SKIP,
                   expiration_date: SKIP, status: SKIP, responded_reason: SKIP,
                   details: SKIP, hidden_details: SKIP, metadata: SKIP,
                   factor_type: SKIP, url: SKIP, links: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @sid = sid unless sid == SKIP
      @account_sid = account_sid unless account_sid == SKIP
      @service_sid = service_sid unless service_sid == SKIP
      @entity_sid = entity_sid unless entity_sid == SKIP
      @identity = identity unless identity == SKIP
      @factor_sid = factor_sid unless factor_sid == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @date_responded = date_responded unless date_responded == SKIP
      @expiration_date = expiration_date unless expiration_date == SKIP
      @status = status unless status == SKIP
      @responded_reason = responded_reason unless responded_reason == SKIP
      @details = details unless details == SKIP
      @hidden_details = hidden_details unless hidden_details == SKIP
      @metadata = metadata unless metadata == SKIP
      @factor_type = factor_type unless factor_type == SKIP
      @url = url unless url == SKIP
      @links = links unless links == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      service_sid = hash.key?('service_sid') ? hash['service_sid'] : SKIP
      entity_sid = hash.key?('entity_sid') ? hash['entity_sid'] : SKIP
      identity = hash.key?('identity') ? hash['identity'] : SKIP
      factor_sid = hash.key?('factor_sid') ? hash['factor_sid'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      date_responded = if hash.key?('date_responded')
                         (DateTimeHelper.from_rfc3339(hash['date_responded']) if hash['date_responded'])
                       else
                         SKIP
                       end
      expiration_date = if hash.key?('expiration_date')
                          (DateTimeHelper.from_rfc3339(hash['expiration_date']) if hash['expiration_date'])
                        else
                          SKIP
                        end
      status = hash.key?('status') ? hash['status'] : SKIP
      responded_reason =
        hash.key?('responded_reason') ? hash['responded_reason'] : SKIP
      details = hash.key?('details') ? hash['details'] : SKIP
      hidden_details =
        hash.key?('hidden_details') ? hash['hidden_details'] : SKIP
      metadata = hash.key?('metadata') ? hash['metadata'] : SKIP
      factor_type = hash.key?('factor_type') ? hash['factor_type'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Challenge.new(sid: sid,
                    account_sid: account_sid,
                    service_sid: service_sid,
                    entity_sid: entity_sid,
                    identity: identity,
                    factor_sid: factor_sid,
                    date_created: date_created,
                    date_updated: date_updated,
                    date_responded: date_responded,
                    expiration_date: expiration_date,
                    status: status,
                    responded_reason: responded_reason,
                    details: details,
                    hidden_details: hidden_details,
                    metadata: metadata,
                    factor_type: factor_type,
                    url: url,
                    links: links,
                    additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    def to_custom_date_responded
      DateTimeHelper.to_rfc3339(date_responded)
    end

    def to_custom_expiration_date
      DateTimeHelper.to_rfc3339(expiration_date)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid}, account_sid: #{@account_sid}, service_sid: #{@service_sid},"\
      " entity_sid: #{@entity_sid}, identity: #{@identity}, factor_sid: #{@factor_sid},"\
      " date_created: #{@date_created}, date_updated: #{@date_updated}, date_responded:"\
      " #{@date_responded}, expiration_date: #{@expiration_date}, status: #{@status},"\
      " responded_reason: #{@responded_reason}, details: #{@details}, hidden_details:"\
      " #{@hidden_details}, metadata: #{@metadata}, factor_type: #{@factor_type}, url: #{@url},"\
      " links: #{@links}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid.inspect}, account_sid: #{@account_sid.inspect}, service_sid:"\
      " #{@service_sid.inspect}, entity_sid: #{@entity_sid.inspect}, identity:"\
      " #{@identity.inspect}, factor_sid: #{@factor_sid.inspect}, date_created:"\
      " #{@date_created.inspect}, date_updated: #{@date_updated.inspect}, date_responded:"\
      " #{@date_responded.inspect}, expiration_date: #{@expiration_date.inspect}, status:"\
      " #{@status.inspect}, responded_reason: #{@responded_reason.inspect}, details:"\
      " #{@details.inspect}, hidden_details: #{@hidden_details.inspect}, metadata:"\
      " #{@metadata.inspect}, factor_type: #{@factor_type.inspect}, url: #{@url.inspect}, links:"\
      " #{@links.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
