# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The routing target of the webhook. Can be ordinary or route internally to
  # Flex
  class ConfigurationWebhookTarget
    CONFIGURATION_WEBHOOK_TARGET = [
      # TODO: Write general description for WEBHOOK
      WEBHOOK = 'webhook'.freeze,

      # TODO: Write general description for FLEX
      FLEX = 'flex'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CONFIGURATION_WEBHOOK_TARGET.include?(value)
    end

    def self.from_value(value, default_value = WEBHOOK)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'webhook' then WEBHOOK
      when 'flex' then FLEX
      else
        default_value
      end
    end
  end
end
