# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ConfigurationWebhook Model.
  class ConfigurationWebhook < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique ID of the
    # [Account](https://www.twilio.com/docs/iam/api/account) responsible for
    # this conversation.
    # @return [String]
    attr_accessor :account_sid

    # The HTTP method to be used when sending a webhook request.
    # @return [ConfigurationWebhookMethod]
    attr_accessor :method

    # The list of webhook event triggers that are enabled for this Service:
    # `onMessageAdded`, `onMessageUpdated`, `onMessageRemoved`, `onMessageAdd`,
    # `onMessageUpdate`, `onMessageRemove`, `onConversationUpdated`,
    # `onConversationRemoved`, `onConversationAdd`, `onConversationAdded`,
    # `onConversationRemove`, `onConversationUpdate`,
    # `onConversationStateUpdated`, `onParticipantAdded`,
    # `onParticipantUpdated`, `onParticipantRemoved`, `onParticipantAdd`,
    # `onParticipantRemove`, `onParticipantUpdate`, `onDeliveryUpdated`,
    # `onUserAdded`, `onUserUpdate`, `onUserUpdated`
    # @return [Array[String]]
    attr_accessor :filters

    # The absolute url the pre-event webhook request should be sent to.
    # @return [String]
    attr_accessor :pre_webhook_url

    # The absolute url the post-event webhook request should be sent to.
    # @return [String]
    attr_accessor :post_webhook_url

    # The routing target of the webhook. Can be ordinary or route internally to
    # Flex
    # @return [ConfigurationWebhookTarget]
    attr_accessor :target

    # An absolute API resource API resource URL for this webhook.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['method'] = 'method'
      @_hash['filters'] = 'filters'
      @_hash['pre_webhook_url'] = 'pre_webhook_url'
      @_hash['post_webhook_url'] = 'post_webhook_url'
      @_hash['target'] = 'target'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        method
        filters
        pre_webhook_url
        post_webhook_url
        target
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        filters
        pre_webhook_url
        post_webhook_url
        url
      ]
    end

    def initialize(account_sid: SKIP, method: SKIP, filters: SKIP,
                   pre_webhook_url: SKIP, post_webhook_url: SKIP, target: SKIP,
                   url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @method = method unless method == SKIP
      @filters = filters unless filters == SKIP
      @pre_webhook_url = pre_webhook_url unless pre_webhook_url == SKIP
      @post_webhook_url = post_webhook_url unless post_webhook_url == SKIP
      @target = target unless target == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      method = hash.key?('method') ? hash['method'] : SKIP
      filters = hash.key?('filters') ? hash['filters'] : SKIP
      pre_webhook_url =
        hash.key?('pre_webhook_url') ? hash['pre_webhook_url'] : SKIP
      post_webhook_url =
        hash.key?('post_webhook_url') ? hash['post_webhook_url'] : SKIP
      target = hash.key?('target') ? hash['target'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConfigurationWebhook.new(account_sid: account_sid,
                               method: method,
                               filters: filters,
                               pre_webhook_url: pre_webhook_url,
                               post_webhook_url: post_webhook_url,
                               target: target,
                               url: url,
                               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, method: #{@method}, filters: #{@filters},"\
      " pre_webhook_url: #{@pre_webhook_url}, post_webhook_url: #{@post_webhook_url}, target:"\
      " #{@target}, url: #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, method: #{@method.inspect}, filters:"\
      " #{@filters.inspect}, pre_webhook_url: #{@pre_webhook_url.inspect}, post_webhook_url:"\
      " #{@post_webhook_url.inspect}, target: #{@target.inspect}, url: #{@url.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
