# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # ConversationMessageReceipt Model.
  class ConversationMessageReceipt < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique ID of the
    # [Account](https://www.twilio.com/docs/iam/api/account) responsible for
    # this participant.
    # @return [String]
    attr_accessor :account_sid

    # The unique ID of the
    # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) for this message.
    # @return [String]
    attr_accessor :conversation_sid

    # A 34 character string that uniquely identifies this resource.
    # @return [String]
    attr_accessor :sid

    # The SID of the message within a
    # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) the delivery receipt belongs to
    # @return [String]
    attr_accessor :message_sid

    # A messaging channel-specific identifier for the message delivered to
    # participant e.g. `SMxx` for SMS, `WAxx` for Whatsapp etc.
    # @return [String]
    attr_accessor :channel_message_sid

    # The unique ID of the participant the delivery receipt belongs to.
    # @return [String]
    attr_accessor :participant_sid

    # The message delivery status, can be `read`, `failed`, `delivered`,
    # `undelivered`, `sent` or null.
    # @return [ConversationMessageReceiptDeliveryStatus]
    attr_accessor :status

    # The message [delivery error
    # code](https://www.twilio.com/docs/sms/api/message-resource#delivery-relate
    # d-errors) for a `failed` status,
    # @return [Integer]
    attr_accessor :error_code

    # The date that this resource was created.
    # @return [DateTime]
    attr_accessor :date_created

    # The date that this resource was last updated. `null` if the delivery
    # receipt has not been updated.
    # @return [DateTime]
    attr_accessor :date_updated

    # An absolute API resource URL for this delivery receipt.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['conversation_sid'] = 'conversation_sid'
      @_hash['sid'] = 'sid'
      @_hash['message_sid'] = 'message_sid'
      @_hash['channel_message_sid'] = 'channel_message_sid'
      @_hash['participant_sid'] = 'participant_sid'
      @_hash['status'] = 'status'
      @_hash['error_code'] = 'error_code'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        conversation_sid
        sid
        message_sid
        channel_message_sid
        participant_sid
        status
        error_code
        date_created
        date_updated
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        conversation_sid
        sid
        message_sid
        channel_message_sid
        participant_sid
        date_created
        date_updated
        url
      ]
    end

    def initialize(account_sid: SKIP, conversation_sid: SKIP, sid: SKIP,
                   message_sid: SKIP, channel_message_sid: SKIP,
                   participant_sid: SKIP, status: SKIP, error_code: 0,
                   date_created: SKIP, date_updated: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @conversation_sid = conversation_sid unless conversation_sid == SKIP
      @sid = sid unless sid == SKIP
      @message_sid = message_sid unless message_sid == SKIP
      @channel_message_sid = channel_message_sid unless channel_message_sid == SKIP
      @participant_sid = participant_sid unless participant_sid == SKIP
      @status = status unless status == SKIP
      @error_code = error_code unless error_code == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      conversation_sid =
        hash.key?('conversation_sid') ? hash['conversation_sid'] : SKIP
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      message_sid = hash.key?('message_sid') ? hash['message_sid'] : SKIP
      channel_message_sid =
        hash.key?('channel_message_sid') ? hash['channel_message_sid'] : SKIP
      participant_sid =
        hash.key?('participant_sid') ? hash['participant_sid'] : SKIP
      status = hash.key?('status') ? hash['status'] : SKIP
      error_code = hash['error_code'] ||= 0
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConversationMessageReceipt.new(account_sid: account_sid,
                                     conversation_sid: conversation_sid,
                                     sid: sid,
                                     message_sid: message_sid,
                                     channel_message_sid: channel_message_sid,
                                     participant_sid: participant_sid,
                                     status: status,
                                     error_code: error_code,
                                     date_created: date_created,
                                     date_updated: date_updated,
                                     url: url,
                                     additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, conversation_sid: #{@conversation_sid}, sid:"\
      " #{@sid}, message_sid: #{@message_sid}, channel_message_sid: #{@channel_message_sid},"\
      " participant_sid: #{@participant_sid}, status: #{@status}, error_code: #{@error_code},"\
      " date_created: #{@date_created}, date_updated: #{@date_updated}, url: #{@url},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, conversation_sid:"\
      " #{@conversation_sid.inspect}, sid: #{@sid.inspect}, message_sid: #{@message_sid.inspect},"\
      " channel_message_sid: #{@channel_message_sid.inspect}, participant_sid:"\
      " #{@participant_sid.inspect}, status: #{@status.inspect}, error_code:"\
      " #{@error_code.inspect}, date_created: #{@date_created.inspect}, date_updated:"\
      " #{@date_updated.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
