# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # Current state of this conversation. Can be either `initializing`, `active`,
  # `inactive` or `closed` and defaults to `active`
  class ConversationState
    CONVERSATION_STATE = [
      # TODO: Write general description for INITIALIZING
      INITIALIZING = 'initializing'.freeze,

      # TODO: Write general description for INACTIVE
      INACTIVE = 'inactive'.freeze,

      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for CLOSED
      CLOSED = 'closed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CONVERSATION_STATE.include?(value)
    end

    def self.from_value(value, default_value = INITIALIZING)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'initializing' then INITIALIZING
      when 'inactive' then INACTIVE
      when 'active' then ACTIVE
      when 'closed' then CLOSED
      else
        default_value
      end
    end
  end
end
