# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # ConversationParticipant Model.
  class ConversationParticipant < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique ID of the
    # [Account](https://www.twilio.com/docs/iam/api/account) responsible for
    # this participant.
    # @return [String]
    attr_accessor :account_sid

    # The unique ID of the
    # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) for this participant.
    # @return [String]
    attr_accessor :conversation_sid

    # A 34 character string that uniquely identifies this resource.
    # @return [String]
    attr_accessor :sid

    # A unique string identifier for the conversation participant as
    # [Conversation
    # User](https://www.twilio.com/docs/conversations/api/user-resource). This
    # parameter is non-null if (and only if) the participant is using the
    # Conversations SDK to communicate. Limited to 256 characters.
    # @return [String]
    attr_accessor :identity

    # An optional string metadata field you can use to store any data you wish.
    # The string value must contain structurally valid JSON if specified.
    # **Note** that if the attributes are not set "{}" will be returned.
    # @return [String]
    attr_accessor :attributes

    # Information about how this participant exchanges messages with the
    # conversation. A JSON parameter consisting of type and address fields of
    # the participant.
    # @return [Object]
    attr_accessor :messaging_binding

    # The SID of a conversation-level
    # [Role](https://www.twilio.com/docs/conversations/api/role-resource) to
    # assign to the participant.
    # @return [String]
    attr_accessor :role_sid

    # The date that this resource was created.
    # @return [DateTime]
    attr_accessor :date_created

    # The date that this resource was last updated.
    # @return [DateTime]
    attr_accessor :date_updated

    # An absolute API resource URL for this participant.
    # @return [String]
    attr_accessor :url

    # Index of last “read” message in the
    # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) for the Participant.
    # @return [Integer]
    attr_accessor :last_read_message_index

    # Timestamp of last “read” message in the
    # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) for the Participant.
    # @return [String]
    attr_accessor :last_read_timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['conversation_sid'] = 'conversation_sid'
      @_hash['sid'] = 'sid'
      @_hash['identity'] = 'identity'
      @_hash['attributes'] = 'attributes'
      @_hash['messaging_binding'] = 'messaging_binding'
      @_hash['role_sid'] = 'role_sid'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['url'] = 'url'
      @_hash['last_read_message_index'] = 'last_read_message_index'
      @_hash['last_read_timestamp'] = 'last_read_timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        conversation_sid
        sid
        identity
        attributes
        messaging_binding
        role_sid
        date_created
        date_updated
        url
        last_read_message_index
        last_read_timestamp
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        conversation_sid
        sid
        identity
        attributes
        messaging_binding
        role_sid
        date_created
        date_updated
        url
        last_read_message_index
        last_read_timestamp
      ]
    end

    def initialize(account_sid: SKIP, conversation_sid: SKIP, sid: SKIP,
                   identity: SKIP, attributes: SKIP, messaging_binding: SKIP,
                   role_sid: SKIP, date_created: SKIP, date_updated: SKIP,
                   url: SKIP, last_read_message_index: SKIP,
                   last_read_timestamp: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @conversation_sid = conversation_sid unless conversation_sid == SKIP
      @sid = sid unless sid == SKIP
      @identity = identity unless identity == SKIP
      @attributes = attributes unless attributes == SKIP
      @messaging_binding = messaging_binding unless messaging_binding == SKIP
      @role_sid = role_sid unless role_sid == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @url = url unless url == SKIP
      @last_read_message_index = last_read_message_index unless last_read_message_index == SKIP
      @last_read_timestamp = last_read_timestamp unless last_read_timestamp == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      conversation_sid =
        hash.key?('conversation_sid') ? hash['conversation_sid'] : SKIP
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      identity = hash.key?('identity') ? hash['identity'] : SKIP
      attributes = hash.key?('attributes') ? hash['attributes'] : SKIP
      messaging_binding =
        hash.key?('messaging_binding') ? hash['messaging_binding'] : SKIP
      role_sid = hash.key?('role_sid') ? hash['role_sid'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      url = hash.key?('url') ? hash['url'] : SKIP
      last_read_message_index =
        hash.key?('last_read_message_index') ? hash['last_read_message_index'] : SKIP
      last_read_timestamp =
        hash.key?('last_read_timestamp') ? hash['last_read_timestamp'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ConversationParticipant.new(account_sid: account_sid,
                                  conversation_sid: conversation_sid,
                                  sid: sid,
                                  identity: identity,
                                  attributes: attributes,
                                  messaging_binding: messaging_binding,
                                  role_sid: role_sid,
                                  date_created: date_created,
                                  date_updated: date_updated,
                                  url: url,
                                  last_read_message_index: last_read_message_index,
                                  last_read_timestamp: last_read_timestamp,
                                  additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, conversation_sid: #{@conversation_sid}, sid:"\
      " #{@sid}, identity: #{@identity}, attributes: #{@attributes}, messaging_binding:"\
      " #{@messaging_binding}, role_sid: #{@role_sid}, date_created: #{@date_created},"\
      " date_updated: #{@date_updated}, url: #{@url}, last_read_message_index:"\
      " #{@last_read_message_index}, last_read_timestamp: #{@last_read_timestamp},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, conversation_sid:"\
      " #{@conversation_sid.inspect}, sid: #{@sid.inspect}, identity: #{@identity.inspect},"\
      " attributes: #{@attributes.inspect}, messaging_binding: #{@messaging_binding.inspect},"\
      " role_sid: #{@role_sid.inspect}, date_created: #{@date_created.inspect}, date_updated:"\
      " #{@date_updated.inspect}, url: #{@url.inspect}, last_read_message_index:"\
      " #{@last_read_message_index.inspect}, last_read_timestamp: #{@last_read_timestamp.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
