# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The target of this webhook: `webhook`, `studio`, `trigger`
  class ConversationScopedWebhookTarget
    CONVERSATION_SCOPED_WEBHOOK_TARGET = [
      # TODO: Write general description for WEBHOOK
      WEBHOOK = 'webhook'.freeze,

      # TODO: Write general description for TRIGGER
      TRIGGER = 'trigger'.freeze,

      # TODO: Write general description for STUDIO
      STUDIO = 'studio'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CONVERSATION_SCOPED_WEBHOOK_TARGET.include?(value)
    end

    def self.from_value(value, default_value = WEBHOOK)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'webhook' then WEBHOOK
      when 'trigger' then TRIGGER
      when 'studio' then STUDIO
      else
        default_value
      end
    end
  end
end
