# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # CredentialPublicKey Model.
  class CredentialPublicKey < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique string that that we created to identify the PublicKey resource.
    # @return [String]
    attr_accessor :sid

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Credential that the PublicKey resource belongs to.
    # @return [String]
    attr_accessor :account_sid

    # The string that you assigned to describe the resource.
    # @return [String]
    attr_accessor :friendly_name

    # The date and time in GMT when the resource was created specified in [RFC
    # 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date and time in GMT when the resource was last updated specified in
    # [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # The URI for this resource, relative to `https://accounts.twilio.com`
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sid'] = 'sid'
      @_hash['account_sid'] = 'account_sid'
      @_hash['friendly_name'] = 'friendly_name'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sid
        account_sid
        friendly_name
        date_created
        date_updated
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        sid
        account_sid
        friendly_name
        date_created
        date_updated
        url
      ]
    end

    def initialize(sid: SKIP, account_sid: SKIP, friendly_name: SKIP,
                   date_created: SKIP, date_updated: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @sid = sid unless sid == SKIP
      @account_sid = account_sid unless account_sid == SKIP
      @friendly_name = friendly_name unless friendly_name == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      friendly_name = hash.key?('friendly_name') ? hash['friendly_name'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      CredentialPublicKey.new(sid: sid,
                              account_sid: account_sid,
                              friendly_name: friendly_name,
                              date_created: date_created,
                              date_updated: date_updated,
                              url: url,
                              additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid}, account_sid: #{@account_sid}, friendly_name:"\
      " #{@friendly_name}, date_created: #{@date_created}, date_updated: #{@date_updated}, url:"\
      " #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid.inspect}, account_sid: #{@account_sid.inspect}, friendly_name:"\
      " #{@friendly_name.inspect}, date_created: #{@date_created.inspect}, date_updated:"\
      " #{@date_updated.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
