# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The Type of this Factor. Currently `push` and `totp` are supported.
  class FactorEnumFactorType
    FACTOR_ENUM_FACTOR_TYPE = [
      # TODO: Write general description for PUSH
      PUSH = 'push'.freeze,

      # TODO: Write general description for TOTP
      TOTP = 'totp'.freeze,

      # TODO: Write general description for PASSKEYS
      PASSKEYS = 'passkeys'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      FACTOR_ENUM_FACTOR_TYPE.include?(value)
    end

    def self.from_value(value, default_value = PUSH)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'push' then PUSH
      when 'totp' then TOTP
      when 'passkeys' then PASSKEYS
      else
        default_value
      end
    end
  end
end
