# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ListTaskChannelResponse Model.
  class ListTaskChannelResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[TaskChannel]]
    attr_accessor :channels

    # TODO: Write general description for this method
    # @return [Meta]
    attr_accessor :meta

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['channels'] = 'channels'
      @_hash['meta'] = 'meta'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        channels
        meta
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(channels: SKIP, meta: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @channels = channels unless channels == SKIP
      @meta = meta unless meta == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      channels = nil
      unless hash['channels'].nil?
        channels = []
        hash['channels'].each do |structure|
          channels << (TaskChannel.from_hash(structure) if structure)
        end
      end

      channels = SKIP unless hash.key?('channels')
      meta = Meta.from_hash(hash['meta']) if hash['meta']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ListTaskChannelResponse.new(channels: channels,
                                  meta: meta,
                                  additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} channels: #{@channels}, meta: #{@meta}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} channels: #{@channels.inspect}, meta: #{@meta.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
