# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ListServiceConversationMessageReceiptResponse Model.
  class ListServiceConversationMessageReceiptResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ServiceConversationMessageReceipt]]
    attr_accessor :delivery_receipts

    # TODO: Write general description for this method
    # @return [Meta]
    attr_accessor :meta

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['delivery_receipts'] = 'delivery_receipts'
      @_hash['meta'] = 'meta'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        delivery_receipts
        meta
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(delivery_receipts: SKIP, meta: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @delivery_receipts = delivery_receipts unless delivery_receipts == SKIP
      @meta = meta unless meta == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      delivery_receipts = nil
      unless hash['delivery_receipts'].nil?
        delivery_receipts = []
        hash['delivery_receipts'].each do |structure|
          delivery_receipts << (ServiceConversationMessageReceipt.from_hash(structure) if structure)
        end
      end

      delivery_receipts = SKIP unless hash.key?('delivery_receipts')
      meta = Meta.from_hash(hash['meta']) if hash['meta']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ListServiceConversationMessageReceiptResponse.new(delivery_receipts: delivery_receipts,
                                                        meta: meta,
                                                        additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} delivery_receipts: #{@delivery_receipts}, meta: #{@meta},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} delivery_receipts: #{@delivery_receipts.inspect}, meta: #{@meta.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
