# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ListCredentialResponse Model.
  class ListCredentialResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Credential]]
    attr_accessor :credentials

    # TODO: Write general description for this method
    # @return [Meta]
    attr_accessor :meta

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['credentials'] = 'credentials'
      @_hash['meta'] = 'meta'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        credentials
        meta
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(credentials: SKIP, meta: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @credentials = credentials unless credentials == SKIP
      @meta = meta unless meta == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      credentials = nil
      unless hash['credentials'].nil?
        credentials = []
        hash['credentials'].each do |structure|
          credentials << (Credential.from_hash(structure) if structure)
        end
      end

      credentials = SKIP unless hash.key?('credentials')
      meta = Meta.from_hash(hash['meta']) if hash['meta']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ListCredentialResponse.new(credentials: credentials,
                                 meta: meta,
                                 additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} credentials: #{@credentials}, meta: #{@meta}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} credentials: #{@credentials.inspect}, meta: #{@meta.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
