# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ListConversationResponse Model.
  class ListConversationResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[Conversation]]
    attr_accessor :conversations

    # TODO: Write general description for this method
    # @return [Meta]
    attr_accessor :meta

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['conversations'] = 'conversations'
      @_hash['meta'] = 'meta'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        conversations
        meta
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(conversations: SKIP, meta: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @conversations = conversations unless conversations == SKIP
      @meta = meta unless meta == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      conversations = nil
      unless hash['conversations'].nil?
        conversations = []
        hash['conversations'].each do |structure|
          conversations << (Conversation.from_hash(structure) if structure)
        end
      end

      conversations = SKIP unless hash.key?('conversations')
      meta = Meta.from_hash(hash['meta']) if hash['meta']

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ListConversationResponse.new(conversations: conversations,
                                   meta: meta,
                                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} conversations: #{@conversations}, meta: #{@meta}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} conversations: #{@conversations.inspect}, meta: #{@meta.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
