# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # Determines if the address can be stored or obfuscated based on privacy
  # settings
  class MessageEnumAddressRetention
    MESSAGE_ENUM_ADDRESS_RETENTION = [
      # TODO: Write general description for RETAIN
      RETAIN = 'retain'.freeze,

      # TODO: Write general description for OBFUSCATE
      OBFUSCATE = 'obfuscate'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      MESSAGE_ENUM_ADDRESS_RETENTION.include?(value)
    end

    def self.from_value(value, default_value = RETAIN)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'retain' then RETAIN
      when 'obfuscate' then OBFUSCATE
      else
        default_value
      end
    end
  end
end
