# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # For Messaging Services only: Include this parameter with a value of `fixed`
  # in conjuction with the `send_time` parameter in order to [schedule a
  # Message](https://www.twilio.com/docs/messaging/features/message-scheduling).
  class MessageEnumScheduleType
    MESSAGE_ENUM_SCHEDULE_TYPE = [
      # TODO: Write general description for FIXED
      FIXED = 'fixed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      MESSAGE_ENUM_SCHEDULE_TYPE.include?(value)
    end

    def self.from_value(value, default_value = FIXED)
      return default_value if value.nil?

      default_value
    end
  end
end
