# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # NewFactorEnumNotificationPlatforms.
  class NewFactorEnumNotificationPlatforms
    NEW_FACTOR_ENUM_NOTIFICATION_PLATFORMS = [
      # TODO: Write general description for APN
      APN = 'apn'.freeze,

      # TODO: Write general description for FCM
      FCM = 'fcm'.freeze,

      # TODO: Write general description for NONE
      NONE = 'none'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NEW_FACTOR_ENUM_NOTIFICATION_PLATFORMS.include?(value)
    end

    def self.from_value(value, default_value = APN)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'apn' then APN
      when 'fcm' then FCM
      when 'none' then NONE
      else
        default_value
      end
    end
  end
end
