# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # ParticipantConversation Model.
  class ParticipantConversation < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique ID of the
    # [Account](https://www.twilio.com/docs/iam/api/account) responsible for
    # this conversation.
    # @return [String]
    attr_accessor :account_sid

    # The unique ID of the [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # this conversation belongs to.
    # @return [String]
    attr_accessor :chat_service_sid

    # The unique ID of the
    # [Participant](https://www.twilio.com/docs/conversations/api/conversation-p
    # articipant-resource).
    # @return [String]
    attr_accessor :participant_sid

    # The unique string that identifies the conversation participant as
    # [Conversation
    # User](https://www.twilio.com/docs/conversations/api/user-resource).
    # @return [String]
    attr_accessor :participant_user_sid

    # A unique string identifier for the conversation participant as
    # [Conversation
    # User](https://www.twilio.com/docs/conversations/api/user-resource). This
    # parameter is non-null if (and only if) the participant is using the
    # Conversations SDK to communicate. Limited to 256 characters.
    # @return [String]
    attr_accessor :participant_identity

    # Information about how this participant exchanges messages with the
    # conversation. A JSON parameter consisting of type and address fields of
    # the participant.
    # @return [Object]
    attr_accessor :participant_messaging_binding

    # The unique ID of the
    # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) this Participant belongs to.
    # @return [String]
    attr_accessor :conversation_sid

    # An application-defined string that uniquely identifies the Conversation
    # resource.
    # @return [String]
    attr_accessor :conversation_unique_name

    # The human-readable name of this conversation, limited to 256 characters.
    # Optional.
    # @return [String]
    attr_accessor :conversation_friendly_name

    # An optional string metadata field you can use to store any data you wish.
    # The string value must contain structurally valid JSON if specified.
    # **Note** that if the attributes are not set "{}" will be returned.
    # @return [String]
    attr_accessor :conversation_attributes

    # The date that this conversation was created, given in ISO 8601 format.
    # @return [DateTime]
    attr_accessor :conversation_date_created

    # The date that this conversation was last updated, given in ISO 8601
    # format.
    # @return [DateTime]
    attr_accessor :conversation_date_updated

    # Identity of the creator of this Conversation.
    # @return [String]
    attr_accessor :conversation_created_by

    # The current state of this User Conversation. One of `inactive`, `active`
    # or `closed`.
    # @return [ParticipantConversationState]
    attr_accessor :conversation_state

    # Timer date values representing state update for this conversation.
    # @return [Object]
    attr_accessor :conversation_timers

    # Contains absolute URLs to access the
    # [participant](https://www.twilio.com/docs/conversations/api/conversation-p
    # articipant-resource) and
    # [conversation](https://www.twilio.com/docs/conversations/api/conversation-
    # resource) of this conversation.
    # @return [Object]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['chat_service_sid'] = 'chat_service_sid'
      @_hash['participant_sid'] = 'participant_sid'
      @_hash['participant_user_sid'] = 'participant_user_sid'
      @_hash['participant_identity'] = 'participant_identity'
      @_hash['participant_messaging_binding'] =
        'participant_messaging_binding'
      @_hash['conversation_sid'] = 'conversation_sid'
      @_hash['conversation_unique_name'] = 'conversation_unique_name'
      @_hash['conversation_friendly_name'] = 'conversation_friendly_name'
      @_hash['conversation_attributes'] = 'conversation_attributes'
      @_hash['conversation_date_created'] = 'conversation_date_created'
      @_hash['conversation_date_updated'] = 'conversation_date_updated'
      @_hash['conversation_created_by'] = 'conversation_created_by'
      @_hash['conversation_state'] = 'conversation_state'
      @_hash['conversation_timers'] = 'conversation_timers'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        chat_service_sid
        participant_sid
        participant_user_sid
        participant_identity
        participant_messaging_binding
        conversation_sid
        conversation_unique_name
        conversation_friendly_name
        conversation_attributes
        conversation_date_created
        conversation_date_updated
        conversation_created_by
        conversation_state
        conversation_timers
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        chat_service_sid
        participant_sid
        participant_user_sid
        participant_identity
        participant_messaging_binding
        conversation_sid
        conversation_unique_name
        conversation_friendly_name
        conversation_attributes
        conversation_date_created
        conversation_date_updated
        conversation_created_by
        conversation_timers
        links
      ]
    end

    def initialize(account_sid: SKIP, chat_service_sid: SKIP,
                   participant_sid: SKIP, participant_user_sid: SKIP,
                   participant_identity: SKIP,
                   participant_messaging_binding: SKIP, conversation_sid: SKIP,
                   conversation_unique_name: SKIP,
                   conversation_friendly_name: SKIP,
                   conversation_attributes: SKIP,
                   conversation_date_created: SKIP,
                   conversation_date_updated: SKIP,
                   conversation_created_by: SKIP, conversation_state: SKIP,
                   conversation_timers: SKIP, links: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @chat_service_sid = chat_service_sid unless chat_service_sid == SKIP
      @participant_sid = participant_sid unless participant_sid == SKIP
      @participant_user_sid = participant_user_sid unless participant_user_sid == SKIP
      @participant_identity = participant_identity unless participant_identity == SKIP
      unless participant_messaging_binding == SKIP
        @participant_messaging_binding =
          participant_messaging_binding
      end
      @conversation_sid = conversation_sid unless conversation_sid == SKIP
      @conversation_unique_name = conversation_unique_name unless conversation_unique_name == SKIP
      unless conversation_friendly_name == SKIP
        @conversation_friendly_name =
          conversation_friendly_name
      end
      @conversation_attributes = conversation_attributes unless conversation_attributes == SKIP
      unless conversation_date_created == SKIP
        @conversation_date_created =
          conversation_date_created
      end
      unless conversation_date_updated == SKIP
        @conversation_date_updated =
          conversation_date_updated
      end
      @conversation_created_by = conversation_created_by unless conversation_created_by == SKIP
      @conversation_state = conversation_state unless conversation_state == SKIP
      @conversation_timers = conversation_timers unless conversation_timers == SKIP
      @links = links unless links == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      chat_service_sid =
        hash.key?('chat_service_sid') ? hash['chat_service_sid'] : SKIP
      participant_sid =
        hash.key?('participant_sid') ? hash['participant_sid'] : SKIP
      participant_user_sid =
        hash.key?('participant_user_sid') ? hash['participant_user_sid'] : SKIP
      participant_identity =
        hash.key?('participant_identity') ? hash['participant_identity'] : SKIP
      participant_messaging_binding =
        hash.key?('participant_messaging_binding') ? hash['participant_messaging_binding'] : SKIP
      conversation_sid =
        hash.key?('conversation_sid') ? hash['conversation_sid'] : SKIP
      conversation_unique_name =
        hash.key?('conversation_unique_name') ? hash['conversation_unique_name'] : SKIP
      conversation_friendly_name =
        hash.key?('conversation_friendly_name') ? hash['conversation_friendly_name'] : SKIP
      conversation_attributes =
        hash.key?('conversation_attributes') ? hash['conversation_attributes'] : SKIP
      conversation_date_created = if hash.key?('conversation_date_created')
                                    (DateTimeHelper.from_rfc3339(hash['conversation_date_created']) if hash['conversation_date_created'])
                                  else
                                    SKIP
                                  end
      conversation_date_updated = if hash.key?('conversation_date_updated')
                                    (DateTimeHelper.from_rfc3339(hash['conversation_date_updated']) if hash['conversation_date_updated'])
                                  else
                                    SKIP
                                  end
      conversation_created_by =
        hash.key?('conversation_created_by') ? hash['conversation_created_by'] : SKIP
      conversation_state =
        hash.key?('conversation_state') ? hash['conversation_state'] : SKIP
      conversation_timers =
        hash.key?('conversation_timers') ? hash['conversation_timers'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ParticipantConversation.new(account_sid: account_sid,
                                  chat_service_sid: chat_service_sid,
                                  participant_sid: participant_sid,
                                  participant_user_sid: participant_user_sid,
                                  participant_identity: participant_identity,
                                  participant_messaging_binding: participant_messaging_binding,
                                  conversation_sid: conversation_sid,
                                  conversation_unique_name: conversation_unique_name,
                                  conversation_friendly_name: conversation_friendly_name,
                                  conversation_attributes: conversation_attributes,
                                  conversation_date_created: conversation_date_created,
                                  conversation_date_updated: conversation_date_updated,
                                  conversation_created_by: conversation_created_by,
                                  conversation_state: conversation_state,
                                  conversation_timers: conversation_timers,
                                  links: links,
                                  additional_properties: additional_properties)
    end

    def to_custom_conversation_date_created
      DateTimeHelper.to_rfc3339(conversation_date_created)
    end

    def to_custom_conversation_date_updated
      DateTimeHelper.to_rfc3339(conversation_date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, chat_service_sid: #{@chat_service_sid},"\
      " participant_sid: #{@participant_sid}, participant_user_sid: #{@participant_user_sid},"\
      " participant_identity: #{@participant_identity}, participant_messaging_binding:"\
      " #{@participant_messaging_binding}, conversation_sid: #{@conversation_sid},"\
      " conversation_unique_name: #{@conversation_unique_name}, conversation_friendly_name:"\
      " #{@conversation_friendly_name}, conversation_attributes: #{@conversation_attributes},"\
      " conversation_date_created: #{@conversation_date_created}, conversation_date_updated:"\
      " #{@conversation_date_updated}, conversation_created_by: #{@conversation_created_by},"\
      " conversation_state: #{@conversation_state}, conversation_timers: #{@conversation_timers},"\
      " links: #{@links}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, chat_service_sid:"\
      " #{@chat_service_sid.inspect}, participant_sid: #{@participant_sid.inspect},"\
      " participant_user_sid: #{@participant_user_sid.inspect}, participant_identity:"\
      " #{@participant_identity.inspect}, participant_messaging_binding:"\
      " #{@participant_messaging_binding.inspect}, conversation_sid: #{@conversation_sid.inspect},"\
      " conversation_unique_name: #{@conversation_unique_name.inspect},"\
      " conversation_friendly_name: #{@conversation_friendly_name.inspect},"\
      " conversation_attributes: #{@conversation_attributes.inspect}, conversation_date_created:"\
      " #{@conversation_date_created.inspect}, conversation_date_updated:"\
      " #{@conversation_date_updated.inspect}, conversation_created_by:"\
      " #{@conversation_created_by.inspect}, conversation_state: #{@conversation_state.inspect},"\
      " conversation_timers: #{@conversation_timers.inspect}, links: #{@links.inspect},"\
      " additional_properties: #{@additional_properties}>"
    end
  end
end
