# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The type of role. Can be: `conversation` for
  # [Conversation](https://www.twilio.com/docs/conversations/api/conversation-re
  # source) roles or `service` for [Conversation
  # Service](https://www.twilio.com/docs/conversations/api/service-resource)
  # roles.
  class RoleRoleType
    ROLE_ROLE_TYPE = [
      # TODO: Write general description for CONVERSATION
      CONVERSATION = 'conversation'.freeze,

      # TODO: Write general description for SERVICE
      SERVICE = 'service'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      ROLE_ROLE_TYPE.include?(value)
    end

    def self.from_value(value, default_value = CONVERSATION)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'conversation' then CONVERSATION
      when 'service' then SERVICE
      else
        default_value
      end
    end
  end
end
