# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # ServiceConfiguration Model.
  class ServiceConfiguration < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique string that we created to identify the Service configuration
    # resource.
    # @return [String]
    attr_accessor :chat_service_sid

    # The conversation-level role assigned to a conversation creator when they
    # join a new conversation. See [Conversation
    # Role](https://www.twilio.com/docs/conversations/api/role-resource) for
    # more info about roles.
    # @return [String]
    attr_accessor :default_conversation_creator_role_sid

    # The conversation-level role assigned to users when they are added to a
    # conversation. See [Conversation
    # Role](https://www.twilio.com/docs/conversations/api/role-resource) for
    # more info about roles.
    # @return [String]
    attr_accessor :default_conversation_role_sid

    # The service-level role assigned to users when they are added to the
    # service. See [Conversation
    # Role](https://www.twilio.com/docs/conversations/api/role-resource) for
    # more info about roles.
    # @return [String]
    attr_accessor :default_chat_service_role_sid

    # An absolute API resource URL for this service configuration.
    # @return [String]
    attr_accessor :url

    # Contains an absolute API resource URL to access the push notifications
    # configuration of this service.
    # @return [Object]
    attr_accessor :links

    # Whether the [Reachability
    # Indicator](https://www.twilio.com/docs/conversations/reachability) is
    # enabled for this Conversations Service. The default is `false`.
    # @return [TrueClass | FalseClass]
    attr_accessor :reachability_enabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['chat_service_sid'] = 'chat_service_sid'
      @_hash['default_conversation_creator_role_sid'] =
        'default_conversation_creator_role_sid'
      @_hash['default_conversation_role_sid'] =
        'default_conversation_role_sid'
      @_hash['default_chat_service_role_sid'] =
        'default_chat_service_role_sid'
      @_hash['url'] = 'url'
      @_hash['links'] = 'links'
      @_hash['reachability_enabled'] = 'reachability_enabled'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        chat_service_sid
        default_conversation_creator_role_sid
        default_conversation_role_sid
        default_chat_service_role_sid
        url
        links
        reachability_enabled
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        chat_service_sid
        default_conversation_creator_role_sid
        default_conversation_role_sid
        default_chat_service_role_sid
        url
        links
        reachability_enabled
      ]
    end

    def initialize(chat_service_sid: SKIP,
                   default_conversation_creator_role_sid: SKIP,
                   default_conversation_role_sid: SKIP,
                   default_chat_service_role_sid: SKIP, url: SKIP, links: SKIP,
                   reachability_enabled: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @chat_service_sid = chat_service_sid unless chat_service_sid == SKIP
      unless default_conversation_creator_role_sid == SKIP
        @default_conversation_creator_role_sid =
          default_conversation_creator_role_sid
      end
      unless default_conversation_role_sid == SKIP
        @default_conversation_role_sid =
          default_conversation_role_sid
      end
      unless default_chat_service_role_sid == SKIP
        @default_chat_service_role_sid =
          default_chat_service_role_sid
      end
      @url = url unless url == SKIP
      @links = links unless links == SKIP
      @reachability_enabled = reachability_enabled unless reachability_enabled == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      chat_service_sid =
        hash.key?('chat_service_sid') ? hash['chat_service_sid'] : SKIP
      default_conversation_creator_role_sid =
        hash.key?('default_conversation_creator_role_sid') ? hash['default_conversation_creator_role_sid'] : SKIP
      default_conversation_role_sid =
        hash.key?('default_conversation_role_sid') ? hash['default_conversation_role_sid'] : SKIP
      default_chat_service_role_sid =
        hash.key?('default_chat_service_role_sid') ? hash['default_chat_service_role_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP
      reachability_enabled =
        hash.key?('reachability_enabled') ? hash['reachability_enabled'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ServiceConfiguration.new(chat_service_sid: chat_service_sid,
                               default_conversation_creator_role_sid: default_conversation_creator_role_sid,
                               default_conversation_role_sid: default_conversation_role_sid,
                               default_chat_service_role_sid: default_chat_service_role_sid,
                               url: url,
                               links: links,
                               reachability_enabled: reachability_enabled,
                               additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} chat_service_sid: #{@chat_service_sid},"\
      " default_conversation_creator_role_sid: #{@default_conversation_creator_role_sid},"\
      " default_conversation_role_sid: #{@default_conversation_role_sid},"\
      " default_chat_service_role_sid: #{@default_chat_service_role_sid}, url: #{@url}, links:"\
      " #{@links}, reachability_enabled: #{@reachability_enabled}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} chat_service_sid: #{@chat_service_sid.inspect},"\
      " default_conversation_creator_role_sid: #{@default_conversation_creator_role_sid.inspect},"\
      " default_conversation_role_sid: #{@default_conversation_role_sid.inspect},"\
      " default_chat_service_role_sid: #{@default_chat_service_role_sid.inspect}, url:"\
      " #{@url.inspect}, links: #{@links.inspect}, reachability_enabled:"\
      " #{@reachability_enabled.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
