# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # ServiceConversationWithParticipants Model.
  class ServiceConversationWithParticipants < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The unique ID of the
    # [Account](https://www.twilio.com/docs/iam/api/account) responsible for
    # this conversation.
    # @return [String]
    attr_accessor :account_sid

    # The unique ID of the [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # this conversation belongs to.
    # @return [String]
    attr_accessor :chat_service_sid

    # The unique ID of the [Messaging
    # Service](https://www.twilio.com/docs/messaging/api/service-resource) this
    # conversation belongs to.
    # @return [String]
    attr_accessor :messaging_service_sid

    # A 34 character string that uniquely identifies this resource.
    # @return [String]
    attr_accessor :sid

    # The human-readable name of this conversation, limited to 256 characters.
    # Optional.
    # @return [String]
    attr_accessor :friendly_name

    # An application-defined string that uniquely identifies the resource. It
    # can be used to address the resource in place of the resource's `sid` in
    # the URL.
    # @return [String]
    attr_accessor :unique_name

    # An optional string metadata field you can use to store any data you wish.
    # The string value must contain structurally valid JSON if specified.
    # **Note** that if the attributes are not set "{}" will be returned.
    # @return [String]
    attr_accessor :attributes

    # Current state of this conversation. Can be either `initializing`,
    # `active`, `inactive` or `closed` and defaults to `active`
    # @return [ServiceConversationWithParticipantsState]
    attr_accessor :state

    # The date that this resource was created.
    # @return [DateTime]
    attr_accessor :date_created

    # The date that this resource was last updated.
    # @return [DateTime]
    attr_accessor :date_updated

    # Timer date values representing state update for this conversation.
    # @return [Object]
    attr_accessor :timers

    # Contains absolute URLs to access the
    # [participants](https://www.twilio.com/docs/conversations/api/conversation-
    # participant-resource),
    # [messages](https://www.twilio.com/docs/conversations/api/conversation-mess
    # age-resource) and
    # [webhooks](https://www.twilio.com/docs/conversations/api/conversation-scop
    # ed-webhook-resource) of this conversation.
    # @return [Object]
    attr_accessor :links

    # Contains absolute URLs to access the
    # [participants](https://www.twilio.com/docs/conversations/api/conversation-
    # participant-resource),
    # [messages](https://www.twilio.com/docs/conversations/api/conversation-mess
    # age-resource) and
    # [webhooks](https://www.twilio.com/docs/conversations/api/conversation-scop
    # ed-webhook-resource) of this conversation.
    # @return [Object]
    attr_accessor :bindings

    # An absolute API resource URL for this conversation.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['chat_service_sid'] = 'chat_service_sid'
      @_hash['messaging_service_sid'] = 'messaging_service_sid'
      @_hash['sid'] = 'sid'
      @_hash['friendly_name'] = 'friendly_name'
      @_hash['unique_name'] = 'unique_name'
      @_hash['attributes'] = 'attributes'
      @_hash['state'] = 'state'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['timers'] = 'timers'
      @_hash['links'] = 'links'
      @_hash['bindings'] = 'bindings'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        chat_service_sid
        messaging_service_sid
        sid
        friendly_name
        unique_name
        attributes
        state
        date_created
        date_updated
        timers
        links
        bindings
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        chat_service_sid
        messaging_service_sid
        sid
        friendly_name
        unique_name
        attributes
        date_created
        date_updated
        timers
        links
        bindings
        url
      ]
    end

    def initialize(account_sid: SKIP, chat_service_sid: SKIP,
                   messaging_service_sid: SKIP, sid: SKIP, friendly_name: SKIP,
                   unique_name: SKIP, attributes: SKIP, state: SKIP,
                   date_created: SKIP, date_updated: SKIP, timers: SKIP,
                   links: SKIP, bindings: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @chat_service_sid = chat_service_sid unless chat_service_sid == SKIP
      @messaging_service_sid = messaging_service_sid unless messaging_service_sid == SKIP
      @sid = sid unless sid == SKIP
      @friendly_name = friendly_name unless friendly_name == SKIP
      @unique_name = unique_name unless unique_name == SKIP
      @attributes = attributes unless attributes == SKIP
      @state = state unless state == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @timers = timers unless timers == SKIP
      @links = links unless links == SKIP
      @bindings = bindings unless bindings == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      chat_service_sid =
        hash.key?('chat_service_sid') ? hash['chat_service_sid'] : SKIP
      messaging_service_sid =
        hash.key?('messaging_service_sid') ? hash['messaging_service_sid'] : SKIP
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      friendly_name = hash.key?('friendly_name') ? hash['friendly_name'] : SKIP
      unique_name = hash.key?('unique_name') ? hash['unique_name'] : SKIP
      attributes = hash.key?('attributes') ? hash['attributes'] : SKIP
      state = hash.key?('state') ? hash['state'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      timers = hash.key?('timers') ? hash['timers'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP
      bindings = hash.key?('bindings') ? hash['bindings'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ServiceConversationWithParticipants.new(account_sid: account_sid,
                                              chat_service_sid: chat_service_sid,
                                              messaging_service_sid: messaging_service_sid,
                                              sid: sid,
                                              friendly_name: friendly_name,
                                              unique_name: unique_name,
                                              attributes: attributes,
                                              state: state,
                                              date_created: date_created,
                                              date_updated: date_updated,
                                              timers: timers,
                                              links: links,
                                              bindings: bindings,
                                              url: url,
                                              additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, chat_service_sid: #{@chat_service_sid},"\
      " messaging_service_sid: #{@messaging_service_sid}, sid: #{@sid}, friendly_name:"\
      " #{@friendly_name}, unique_name: #{@unique_name}, attributes: #{@attributes}, state:"\
      " #{@state}, date_created: #{@date_created}, date_updated: #{@date_updated}, timers:"\
      " #{@timers}, links: #{@links}, bindings: #{@bindings}, url: #{@url}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, chat_service_sid:"\
      " #{@chat_service_sid.inspect}, messaging_service_sid: #{@messaging_service_sid.inspect},"\
      " sid: #{@sid.inspect}, friendly_name: #{@friendly_name.inspect}, unique_name:"\
      " #{@unique_name.inspect}, attributes: #{@attributes.inspect}, state: #{@state.inspect},"\
      " date_created: #{@date_created.inspect}, date_updated: #{@date_updated.inspect}, timers:"\
      " #{@timers.inspect}, links: #{@links.inspect}, bindings: #{@bindings.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
