# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # ServiceBinding Model.
  class ServiceBinding < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # A 34 character string that uniquely identifies this resource.
    # @return [String]
    attr_accessor :sid

    # The unique ID of the
    # [Account](https://www.twilio.com/docs/iam/api/account) responsible for
    # this binding.
    # @return [String]
    attr_accessor :account_sid

    # The SID of the [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource)
    # the Binding resource is associated with.
    # @return [String]
    attr_accessor :chat_service_sid

    # The SID of the
    # [Credential](https://www.twilio.com/docs/conversations/api/credential-reso
    # urce) for the binding. See [push notification
    # configuration](https://www.twilio.com/docs/chat/push-notification-configur
    # ation) for more info.
    # @return [String]
    attr_accessor :credential_sid

    # The date that this resource was created.
    # @return [DateTime]
    attr_accessor :date_created

    # The date that this resource was last updated.
    # @return [DateTime]
    attr_accessor :date_updated

    # The unique endpoint identifier for the Binding. The format of this value
    # depends on the `binding_type`.
    # @return [String]
    attr_accessor :endpoint

    # The application-defined string that uniquely identifies the [Conversation
    # User](https://www.twilio.com/docs/conversations/api/user-resource) within
    # the [Conversation
    # Service](https://www.twilio.com/docs/conversations/api/service-resource).
    # See [access
    # tokens](https://www.twilio.com/docs/conversations/create-tokens) for more
    # info.
    # @return [String]
    attr_accessor :identity

    # The push technology to use for the Binding. Can be: `apn`, `gcm`, `fcm`,
    # or `twilsock`.  See [push notification
    # configuration](https://www.twilio.com/docs/chat/push-notification-configur
    # ation) for more info.
    # @return [ServiceBindingBindingType]
    attr_accessor :binding_type

    # The [Conversation message
    # types](https://www.twilio.com/docs/chat/push-notification-configuration#pu
    # sh-types) the binding is subscribed to.
    # @return [Array[String]]
    attr_accessor :message_types

    # An absolute API resource URL for this binding.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sid'] = 'sid'
      @_hash['account_sid'] = 'account_sid'
      @_hash['chat_service_sid'] = 'chat_service_sid'
      @_hash['credential_sid'] = 'credential_sid'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['endpoint'] = 'endpoint'
      @_hash['identity'] = 'identity'
      @_hash['binding_type'] = 'binding_type'
      @_hash['message_types'] = 'message_types'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sid
        account_sid
        chat_service_sid
        credential_sid
        date_created
        date_updated
        endpoint
        identity
        binding_type
        message_types
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        sid
        account_sid
        chat_service_sid
        credential_sid
        date_created
        date_updated
        endpoint
        identity
        message_types
        url
      ]
    end

    def initialize(sid: SKIP, account_sid: SKIP, chat_service_sid: SKIP,
                   credential_sid: SKIP, date_created: SKIP, date_updated: SKIP,
                   endpoint: SKIP, identity: SKIP, binding_type: SKIP,
                   message_types: SKIP, url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @sid = sid unless sid == SKIP
      @account_sid = account_sid unless account_sid == SKIP
      @chat_service_sid = chat_service_sid unless chat_service_sid == SKIP
      @credential_sid = credential_sid unless credential_sid == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @endpoint = endpoint unless endpoint == SKIP
      @identity = identity unless identity == SKIP
      @binding_type = binding_type unless binding_type == SKIP
      @message_types = message_types unless message_types == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      chat_service_sid =
        hash.key?('chat_service_sid') ? hash['chat_service_sid'] : SKIP
      credential_sid =
        hash.key?('credential_sid') ? hash['credential_sid'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      endpoint = hash.key?('endpoint') ? hash['endpoint'] : SKIP
      identity = hash.key?('identity') ? hash['identity'] : SKIP
      binding_type = hash.key?('binding_type') ? hash['binding_type'] : SKIP
      message_types = hash.key?('message_types') ? hash['message_types'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      ServiceBinding.new(sid: sid,
                         account_sid: account_sid,
                         chat_service_sid: chat_service_sid,
                         credential_sid: credential_sid,
                         date_created: date_created,
                         date_updated: date_updated,
                         endpoint: endpoint,
                         identity: identity,
                         binding_type: binding_type,
                         message_types: message_types,
                         url: url,
                         additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid}, account_sid: #{@account_sid}, chat_service_sid:"\
      " #{@chat_service_sid}, credential_sid: #{@credential_sid}, date_created: #{@date_created},"\
      " date_updated: #{@date_updated}, endpoint: #{@endpoint}, identity: #{@identity},"\
      " binding_type: #{@binding_type}, message_types: #{@message_types}, url: #{@url},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid.inspect}, account_sid: #{@account_sid.inspect},"\
      " chat_service_sid: #{@chat_service_sid.inspect}, credential_sid:"\
      " #{@credential_sid.inspect}, date_created: #{@date_created.inspect}, date_updated:"\
      " #{@date_updated.inspect}, endpoint: #{@endpoint.inspect}, identity: #{@identity.inspect},"\
      " binding_type: #{@binding_type.inspect}, message_types: #{@message_types.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
