# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The HTTP method to be used when sending a webhook request. One of `GET` or
  # `POST`.
  class ServiceWebhookConfigurationMethod
    SERVICE_WEBHOOK_CONFIGURATION_METHOD = [
      # TODO: Write general description for GET
      GET = 'GET'.freeze,

      # TODO: Write general description for POST
      POST = 'POST'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      SERVICE_WEBHOOK_CONFIGURATION_METHOD.include?(value)
    end

    def self.from_value(value, default_value = GET)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'get' then GET
      when 'post' then POST
      else
        default_value
      end
    end
  end
end
