# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # TaskQueueRealTimeStatistics Model.
  class TaskQueueRealTimeStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the TaskQueue resource.
    # @return [String]
    attr_accessor :account_sid

    # The number of current Workers by Activity.
    # @return [Array[Object]]
    attr_accessor :activity_statistics

    # The age of the longest waiting Task.
    # @return [Integer]
    attr_accessor :longest_task_waiting_age

    # The SID of the longest waiting Task.
    # @return [String]
    attr_accessor :longest_task_waiting_sid

    # The relative age in the TaskQueue for the longest waiting Task.
    # Calculation is based on the time when the Task entered the TaskQueue.
    # @return [Integer]
    attr_accessor :longest_relative_task_age_in_queue

    # The Task SID of the Task waiting in the TaskQueue the longest. Calculation
    # is based on the time when the Task entered the TaskQueue.
    # @return [String]
    attr_accessor :longest_relative_task_sid_in_queue

    # The SID of the TaskQueue from which these statistics were calculated.
    # @return [String]
    attr_accessor :task_queue_sid

    # The number of Tasks by priority. For example: `{"0": "10", "99": "5"}`
    # shows 10 Tasks at priority 0 and 5 at priority 99.
    # @return [Object]
    attr_accessor :tasks_by_priority

    # The number of Tasks by their current status. For example: `{"pending":
    # "1", "reserved": "3", "assigned": "2", "completed": "5"}`.
    # @return [Object]
    attr_accessor :tasks_by_status

    # The total number of Workers in the TaskQueue with an `available` status.
    # Workers with an `available` status may already have active interactions or
    # may have none.
    # @return [Integer]
    attr_accessor :total_available_workers

    # The total number of Workers eligible for Tasks in the TaskQueue,
    # independent of their Activity state.
    # @return [Integer]
    attr_accessor :total_eligible_workers

    # The total number of Tasks.
    # @return [Integer]
    attr_accessor :total_tasks

    # The SID of the Workspace that contains the TaskQueue.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the TaskQueue statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['activity_statistics'] = 'activity_statistics'
      @_hash['longest_task_waiting_age'] = 'longest_task_waiting_age'
      @_hash['longest_task_waiting_sid'] = 'longest_task_waiting_sid'
      @_hash['longest_relative_task_age_in_queue'] =
        'longest_relative_task_age_in_queue'
      @_hash['longest_relative_task_sid_in_queue'] =
        'longest_relative_task_sid_in_queue'
      @_hash['task_queue_sid'] = 'task_queue_sid'
      @_hash['tasks_by_priority'] = 'tasks_by_priority'
      @_hash['tasks_by_status'] = 'tasks_by_status'
      @_hash['total_available_workers'] = 'total_available_workers'
      @_hash['total_eligible_workers'] = 'total_eligible_workers'
      @_hash['total_tasks'] = 'total_tasks'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        activity_statistics
        longest_task_waiting_age
        longest_task_waiting_sid
        longest_relative_task_age_in_queue
        longest_relative_task_sid_in_queue
        task_queue_sid
        tasks_by_priority
        tasks_by_status
        total_available_workers
        total_eligible_workers
        total_tasks
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        activity_statistics
        longest_task_waiting_sid
        longest_relative_task_sid_in_queue
        task_queue_sid
        tasks_by_priority
        tasks_by_status
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, activity_statistics: SKIP,
                   longest_task_waiting_age: 0, longest_task_waiting_sid: SKIP,
                   longest_relative_task_age_in_queue: 0,
                   longest_relative_task_sid_in_queue: SKIP,
                   task_queue_sid: SKIP, tasks_by_priority: SKIP,
                   tasks_by_status: SKIP, total_available_workers: 0,
                   total_eligible_workers: 0, total_tasks: 0,
                   workspace_sid: SKIP, url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @activity_statistics = activity_statistics unless activity_statistics == SKIP
      @longest_task_waiting_age = longest_task_waiting_age unless longest_task_waiting_age == SKIP
      @longest_task_waiting_sid = longest_task_waiting_sid unless longest_task_waiting_sid == SKIP
      unless longest_relative_task_age_in_queue == SKIP
        @longest_relative_task_age_in_queue =
          longest_relative_task_age_in_queue
      end
      unless longest_relative_task_sid_in_queue == SKIP
        @longest_relative_task_sid_in_queue =
          longest_relative_task_sid_in_queue
      end
      @task_queue_sid = task_queue_sid unless task_queue_sid == SKIP
      @tasks_by_priority = tasks_by_priority unless tasks_by_priority == SKIP
      @tasks_by_status = tasks_by_status unless tasks_by_status == SKIP
      @total_available_workers = total_available_workers unless total_available_workers == SKIP
      @total_eligible_workers = total_eligible_workers unless total_eligible_workers == SKIP
      @total_tasks = total_tasks unless total_tasks == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      activity_statistics =
        hash.key?('activity_statistics') ? hash['activity_statistics'] : SKIP
      longest_task_waiting_age = hash['longest_task_waiting_age'] ||= 0
      longest_task_waiting_sid =
        hash.key?('longest_task_waiting_sid') ? hash['longest_task_waiting_sid'] : SKIP
      longest_relative_task_age_in_queue =
        hash['longest_relative_task_age_in_queue'] ||= 0
      longest_relative_task_sid_in_queue =
        hash.key?('longest_relative_task_sid_in_queue') ? hash['longest_relative_task_sid_in_queue'] : SKIP
      task_queue_sid =
        hash.key?('task_queue_sid') ? hash['task_queue_sid'] : SKIP
      tasks_by_priority =
        hash.key?('tasks_by_priority') ? hash['tasks_by_priority'] : SKIP
      tasks_by_status =
        hash.key?('tasks_by_status') ? hash['tasks_by_status'] : SKIP
      total_available_workers = hash['total_available_workers'] ||= 0
      total_eligible_workers = hash['total_eligible_workers'] ||= 0
      total_tasks = hash['total_tasks'] ||= 0
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      TaskQueueRealTimeStatistics.new(account_sid: account_sid,
                                      activity_statistics: activity_statistics,
                                      longest_task_waiting_age: longest_task_waiting_age,
                                      longest_task_waiting_sid: longest_task_waiting_sid,
                                      longest_relative_task_age_in_queue: longest_relative_task_age_in_queue,
                                      longest_relative_task_sid_in_queue: longest_relative_task_sid_in_queue,
                                      task_queue_sid: task_queue_sid,
                                      tasks_by_priority: tasks_by_priority,
                                      tasks_by_status: tasks_by_status,
                                      total_available_workers: total_available_workers,
                                      total_eligible_workers: total_eligible_workers,
                                      total_tasks: total_tasks,
                                      workspace_sid: workspace_sid,
                                      url: url,
                                      additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, activity_statistics: #{@activity_statistics},"\
      " longest_task_waiting_age: #{@longest_task_waiting_age}, longest_task_waiting_sid:"\
      " #{@longest_task_waiting_sid}, longest_relative_task_age_in_queue:"\
      " #{@longest_relative_task_age_in_queue}, longest_relative_task_sid_in_queue:"\
      " #{@longest_relative_task_sid_in_queue}, task_queue_sid: #{@task_queue_sid},"\
      " tasks_by_priority: #{@tasks_by_priority}, tasks_by_status: #{@tasks_by_status},"\
      " total_available_workers: #{@total_available_workers}, total_eligible_workers:"\
      " #{@total_eligible_workers}, total_tasks: #{@total_tasks}, workspace_sid:"\
      " #{@workspace_sid}, url: #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, activity_statistics:"\
      " #{@activity_statistics.inspect}, longest_task_waiting_age:"\
      " #{@longest_task_waiting_age.inspect}, longest_task_waiting_sid:"\
      " #{@longest_task_waiting_sid.inspect}, longest_relative_task_age_in_queue:"\
      " #{@longest_relative_task_age_in_queue.inspect}, longest_relative_task_sid_in_queue:"\
      " #{@longest_relative_task_sid_in_queue.inspect}, task_queue_sid:"\
      " #{@task_queue_sid.inspect}, tasks_by_priority: #{@tasks_by_priority.inspect},"\
      " tasks_by_status: #{@tasks_by_status.inspect}, total_available_workers:"\
      " #{@total_available_workers.inspect}, total_eligible_workers:"\
      " #{@total_eligible_workers.inspect}, total_tasks: #{@total_tasks.inspect}, workspace_sid:"\
      " #{@workspace_sid.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
