# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # TaskRouterTask Model.
  class TaskRouterTask < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Task resource.
    # @return [String]
    attr_accessor :account_sid

    # The number of seconds since the Task was created.
    # @return [Integer]
    attr_accessor :age

    # The current status of the Task's assignment. Can be: `pending`,
    # `reserved`, `assigned`, `canceled`, `wrapping`, or `completed`.
    # @return [TaskStatus]
    attr_accessor :assignment_status

    # The JSON string with custom attributes of the work. **Note** If this
    # property has been assigned a value, it will only be displayed in FETCH
    # action that returns a single resource. Otherwise, it will be null.
    # @return [String]
    attr_accessor :attributes

    # An object that contains the [Add-on](https://www.twilio.com/docs/add-ons)
    # data for all installed Add-ons.
    # @return [String]
    attr_accessor :addons

    # The date and time in GMT when the resource was created specified in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date and time in GMT when the resource was last updated specified in
    # [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # The date and time in GMT when the Task entered the TaskQueue, specified in
    # [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :task_queue_entered_date

    # The current priority score of the Task as assigned to a Worker by the
    # workflow. Tasks with higher priority values will be assigned before Tasks
    # with lower values.
    # @return [Integer]
    attr_accessor :priority

    # The reason the Task was canceled or completed, if applicable.
    # @return [String]
    attr_accessor :reason

    # The unique string that we created to identify the Task resource.
    # @return [String]
    attr_accessor :sid

    # The SID of the TaskQueue.
    # @return [String]
    attr_accessor :task_queue_sid

    # The friendly name of the TaskQueue.
    # @return [String]
    attr_accessor :task_queue_friendly_name

    # The SID of the TaskChannel.
    # @return [String]
    attr_accessor :task_channel_sid

    # The unique name of the TaskChannel.
    # @return [String]
    attr_accessor :task_channel_unique_name

    # The amount of time in seconds that the Task can live before being
    # assigned.
    # @return [Integer]
    attr_accessor :timeout

    # The SID of the Workflow that is controlling the Task.
    # @return [String]
    attr_accessor :workflow_sid

    # The friendly name of the Workflow that is controlling the Task.
    # @return [String]
    attr_accessor :workflow_friendly_name

    # The SID of the Workspace that contains the Task.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the Task resource.
    # @return [String]
    attr_accessor :url

    # The URLs of related resources.
    # @return [Object]
    attr_accessor :links

    # The date and time in GMT indicating the ordering for routing of the Task
    # specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :virtual_start_time

    # A boolean that indicates if the Task should respect a Worker's capacity
    # and availability during assignment. This field can only be used when the
    # `RoutingTarget` field is set to a Worker SID. By setting `IgnoreCapacity`
    # to a value of `true`, `1`, or `yes`, the Task will be routed to the Worker
    # without respecting their capacity and availability. Any other value will
    # enforce the Worker's capacity and availability. The default value of
    # `IgnoreCapacity` is `true` when the `RoutingTarget` is set to a Worker
    # SID.
    # @return [TrueClass | FalseClass]
    attr_accessor :ignore_capacity

    # A SID of a Worker, Queue, or Workflow to route a Task to
    # @return [String]
    attr_accessor :routing_target

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['age'] = 'age'
      @_hash['assignment_status'] = 'assignment_status'
      @_hash['attributes'] = 'attributes'
      @_hash['addons'] = 'addons'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['task_queue_entered_date'] = 'task_queue_entered_date'
      @_hash['priority'] = 'priority'
      @_hash['reason'] = 'reason'
      @_hash['sid'] = 'sid'
      @_hash['task_queue_sid'] = 'task_queue_sid'
      @_hash['task_queue_friendly_name'] = 'task_queue_friendly_name'
      @_hash['task_channel_sid'] = 'task_channel_sid'
      @_hash['task_channel_unique_name'] = 'task_channel_unique_name'
      @_hash['timeout'] = 'timeout'
      @_hash['workflow_sid'] = 'workflow_sid'
      @_hash['workflow_friendly_name'] = 'workflow_friendly_name'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash['links'] = 'links'
      @_hash['virtual_start_time'] = 'virtual_start_time'
      @_hash['ignore_capacity'] = 'ignore_capacity'
      @_hash['routing_target'] = 'routing_target'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        age
        assignment_status
        attributes
        addons
        date_created
        date_updated
        task_queue_entered_date
        priority
        reason
        sid
        task_queue_sid
        task_queue_friendly_name
        task_channel_sid
        task_channel_unique_name
        timeout
        workflow_sid
        workflow_friendly_name
        workspace_sid
        url
        links
        virtual_start_time
        ignore_capacity
        routing_target
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        attributes
        addons
        date_created
        date_updated
        task_queue_entered_date
        reason
        sid
        task_queue_sid
        task_queue_friendly_name
        task_channel_sid
        task_channel_unique_name
        workflow_sid
        workflow_friendly_name
        workspace_sid
        url
        links
        virtual_start_time
        ignore_capacity
        routing_target
      ]
    end

    def initialize(account_sid: SKIP, age: 0, assignment_status: SKIP,
                   attributes: SKIP, addons: SKIP, date_created: SKIP,
                   date_updated: SKIP, task_queue_entered_date: SKIP,
                   priority: 0, reason: SKIP, sid: SKIP, task_queue_sid: SKIP,
                   task_queue_friendly_name: SKIP, task_channel_sid: SKIP,
                   task_channel_unique_name: SKIP, timeout: 0,
                   workflow_sid: SKIP, workflow_friendly_name: SKIP,
                   workspace_sid: SKIP, url: SKIP, links: SKIP,
                   virtual_start_time: SKIP, ignore_capacity: SKIP,
                   routing_target: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @age = age unless age == SKIP
      @assignment_status = assignment_status unless assignment_status == SKIP
      @attributes = attributes unless attributes == SKIP
      @addons = addons unless addons == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @task_queue_entered_date = task_queue_entered_date unless task_queue_entered_date == SKIP
      @priority = priority unless priority == SKIP
      @reason = reason unless reason == SKIP
      @sid = sid unless sid == SKIP
      @task_queue_sid = task_queue_sid unless task_queue_sid == SKIP
      @task_queue_friendly_name = task_queue_friendly_name unless task_queue_friendly_name == SKIP
      @task_channel_sid = task_channel_sid unless task_channel_sid == SKIP
      @task_channel_unique_name = task_channel_unique_name unless task_channel_unique_name == SKIP
      @timeout = timeout unless timeout == SKIP
      @workflow_sid = workflow_sid unless workflow_sid == SKIP
      @workflow_friendly_name = workflow_friendly_name unless workflow_friendly_name == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @links = links unless links == SKIP
      @virtual_start_time = virtual_start_time unless virtual_start_time == SKIP
      @ignore_capacity = ignore_capacity unless ignore_capacity == SKIP
      @routing_target = routing_target unless routing_target == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      age = hash['age'] ||= 0
      assignment_status =
        hash.key?('assignment_status') ? hash['assignment_status'] : SKIP
      attributes = hash.key?('attributes') ? hash['attributes'] : SKIP
      addons = hash.key?('addons') ? hash['addons'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      task_queue_entered_date = if hash.key?('task_queue_entered_date')
                                  (DateTimeHelper.from_rfc3339(hash['task_queue_entered_date']) if hash['task_queue_entered_date'])
                                else
                                  SKIP
                                end
      priority = hash['priority'] ||= 0
      reason = hash.key?('reason') ? hash['reason'] : SKIP
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      task_queue_sid =
        hash.key?('task_queue_sid') ? hash['task_queue_sid'] : SKIP
      task_queue_friendly_name =
        hash.key?('task_queue_friendly_name') ? hash['task_queue_friendly_name'] : SKIP
      task_channel_sid =
        hash.key?('task_channel_sid') ? hash['task_channel_sid'] : SKIP
      task_channel_unique_name =
        hash.key?('task_channel_unique_name') ? hash['task_channel_unique_name'] : SKIP
      timeout = hash['timeout'] ||= 0
      workflow_sid = hash.key?('workflow_sid') ? hash['workflow_sid'] : SKIP
      workflow_friendly_name =
        hash.key?('workflow_friendly_name') ? hash['workflow_friendly_name'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP
      virtual_start_time = if hash.key?('virtual_start_time')
                             (DateTimeHelper.from_rfc3339(hash['virtual_start_time']) if hash['virtual_start_time'])
                           else
                             SKIP
                           end
      ignore_capacity =
        hash.key?('ignore_capacity') ? hash['ignore_capacity'] : SKIP
      routing_target =
        hash.key?('routing_target') ? hash['routing_target'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      TaskRouterTask.new(account_sid: account_sid,
                         age: age,
                         assignment_status: assignment_status,
                         attributes: attributes,
                         addons: addons,
                         date_created: date_created,
                         date_updated: date_updated,
                         task_queue_entered_date: task_queue_entered_date,
                         priority: priority,
                         reason: reason,
                         sid: sid,
                         task_queue_sid: task_queue_sid,
                         task_queue_friendly_name: task_queue_friendly_name,
                         task_channel_sid: task_channel_sid,
                         task_channel_unique_name: task_channel_unique_name,
                         timeout: timeout,
                         workflow_sid: workflow_sid,
                         workflow_friendly_name: workflow_friendly_name,
                         workspace_sid: workspace_sid,
                         url: url,
                         links: links,
                         virtual_start_time: virtual_start_time,
                         ignore_capacity: ignore_capacity,
                         routing_target: routing_target,
                         additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    def to_custom_task_queue_entered_date
      DateTimeHelper.to_rfc3339(task_queue_entered_date)
    end

    def to_custom_virtual_start_time
      DateTimeHelper.to_rfc3339(virtual_start_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, age: #{@age}, assignment_status:"\
      " #{@assignment_status}, attributes: #{@attributes}, addons: #{@addons}, date_created:"\
      " #{@date_created}, date_updated: #{@date_updated}, task_queue_entered_date:"\
      " #{@task_queue_entered_date}, priority: #{@priority}, reason: #{@reason}, sid: #{@sid},"\
      " task_queue_sid: #{@task_queue_sid}, task_queue_friendly_name:"\
      " #{@task_queue_friendly_name}, task_channel_sid: #{@task_channel_sid},"\
      " task_channel_unique_name: #{@task_channel_unique_name}, timeout: #{@timeout},"\
      " workflow_sid: #{@workflow_sid}, workflow_friendly_name: #{@workflow_friendly_name},"\
      " workspace_sid: #{@workspace_sid}, url: #{@url}, links: #{@links}, virtual_start_time:"\
      " #{@virtual_start_time}, ignore_capacity: #{@ignore_capacity}, routing_target:"\
      " #{@routing_target}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, age: #{@age.inspect},"\
      " assignment_status: #{@assignment_status.inspect}, attributes: #{@attributes.inspect},"\
      " addons: #{@addons.inspect}, date_created: #{@date_created.inspect}, date_updated:"\
      " #{@date_updated.inspect}, task_queue_entered_date: #{@task_queue_entered_date.inspect},"\
      " priority: #{@priority.inspect}, reason: #{@reason.inspect}, sid: #{@sid.inspect},"\
      " task_queue_sid: #{@task_queue_sid.inspect}, task_queue_friendly_name:"\
      " #{@task_queue_friendly_name.inspect}, task_channel_sid: #{@task_channel_sid.inspect},"\
      " task_channel_unique_name: #{@task_channel_unique_name.inspect}, timeout:"\
      " #{@timeout.inspect}, workflow_sid: #{@workflow_sid.inspect}, workflow_friendly_name:"\
      " #{@workflow_friendly_name.inspect}, workspace_sid: #{@workspace_sid.inspect}, url:"\
      " #{@url.inspect}, links: #{@links.inspect}, virtual_start_time:"\
      " #{@virtual_start_time.inspect}, ignore_capacity: #{@ignore_capacity.inspect},"\
      " routing_target: #{@routing_target.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
