# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # TaskQueueStatistics Model.
  class TaskQueueStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the TaskQueue resource.
    # @return [String]
    attr_accessor :account_sid

    # An object that contains the cumulative statistics for the TaskQueue.
    # @return [Object]
    attr_accessor :cumulative

    # An object that contains the real-time statistics for the TaskQueue.
    # @return [Object]
    attr_accessor :realtime

    # The SID of the TaskQueue from which these statistics were calculated.
    # @return [String]
    attr_accessor :task_queue_sid

    # The SID of the Workspace that contains the TaskQueue.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the TaskQueue statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['cumulative'] = 'cumulative'
      @_hash['realtime'] = 'realtime'
      @_hash['task_queue_sid'] = 'task_queue_sid'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        cumulative
        realtime
        task_queue_sid
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        cumulative
        realtime
        task_queue_sid
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, cumulative: SKIP, realtime: SKIP,
                   task_queue_sid: SKIP, workspace_sid: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @cumulative = cumulative unless cumulative == SKIP
      @realtime = realtime unless realtime == SKIP
      @task_queue_sid = task_queue_sid unless task_queue_sid == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      cumulative = hash.key?('cumulative') ? hash['cumulative'] : SKIP
      realtime = hash.key?('realtime') ? hash['realtime'] : SKIP
      task_queue_sid =
        hash.key?('task_queue_sid') ? hash['task_queue_sid'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      TaskQueueStatistics.new(account_sid: account_sid,
                              cumulative: cumulative,
                              realtime: realtime,
                              task_queue_sid: task_queue_sid,
                              workspace_sid: workspace_sid,
                              url: url,
                              additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, cumulative: #{@cumulative}, realtime:"\
      " #{@realtime}, task_queue_sid: #{@task_queue_sid}, workspace_sid: #{@workspace_sid}, url:"\
      " #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, cumulative: #{@cumulative.inspect},"\
      " realtime: #{@realtime.inspect}, task_queue_sid: #{@task_queue_sid.inspect}, workspace_sid:"\
      " #{@workspace_sid.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
