# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The current state of this User Conversation. One of `inactive`, `active` or
  # `closed`.
  class UserConversationState
    USER_CONVERSATION_STATE = [
      # TODO: Write general description for INACTIVE
      INACTIVE = 'inactive'.freeze,

      # TODO: Write general description for ACTIVE
      ACTIVE = 'active'.freeze,

      # TODO: Write general description for CLOSED
      CLOSED = 'closed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      USER_CONVERSATION_STATE.include?(value)
    end

    def self.from_value(value, default_value = INACTIVE)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'inactive' then INACTIVE
      when 'active' then ACTIVE
      when 'closed' then CLOSED
      else
        default_value
      end
    end
  end
end
