# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # A string specifying the conversion status of the verification. A conversion
  # happens when the user is able to provide the correct code. Possible values
  # are `CONVERTED` and `UNCONVERTED`.
  class VerificationAttemptEnumConversionStatus
    VERIFICATION_ATTEMPT_ENUM_CONVERSION_STATUS = [
      # TODO: Write general description for CONVERTED
      CONVERTED = 'converted'.freeze,

      # TODO: Write general description for UNCONVERTED
      UNCONVERTED = 'unconverted'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      VERIFICATION_ATTEMPT_ENUM_CONVERSION_STATUS.include?(value)
    end

    def self.from_value(value, default_value = CONVERTED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'converted' then CONVERTED
      when 'unconverted' then UNCONVERTED
      else
        default_value
      end
    end
  end
end
