# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # The status of the Message. Possible values: `accepted`, `scheduled`,
  # `canceled`, `queued`, `sending`, `sent`, `failed`, `delivered`,
  # `undelivered`, `receiving`, `received`, or `read` (WhatsApp only). For more
  # information, See [detailed
  # descriptions](https://www.twilio.com/docs/sms/api/message-resource#message-s
  # tatus-values).
  class VerificationAttemptEnumMessageStatus
    VERIFICATION_ATTEMPT_ENUM_MESSAGE_STATUS = [
      # TODO: Write general description for QUEUED
      QUEUED = 'queued'.freeze,

      # TODO: Write general description for SENDING
      SENDING = 'sending'.freeze,

      # TODO: Write general description for SENT
      SENT = 'sent'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze,

      # TODO: Write general description for UNDELIVERED
      UNDELIVERED = 'undelivered'.freeze,

      # TODO: Write general description for RECEIVING
      RECEIVING = 'receiving'.freeze,

      # TODO: Write general description for RECEIVED
      RECEIVED = 'received'.freeze,

      # TODO: Write general description for ACCEPTED
      ACCEPTED = 'accepted'.freeze,

      # TODO: Write general description for SCHEDULED
      SCHEDULED = 'scheduled'.freeze,

      # TODO: Write general description for READ
      READ = 'read'.freeze,

      # TODO: Write general description for PARTIALLY_DELIVERED
      PARTIALLY_DELIVERED = 'partially_delivered'.freeze,

      # TODO: Write general description for CANCELED
      CANCELED = 'canceled'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      VERIFICATION_ATTEMPT_ENUM_MESSAGE_STATUS.include?(value)
    end

    def self.from_value(value, default_value = QUEUED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'queued' then QUEUED
      when 'sending' then SENDING
      when 'sent' then SENT
      when 'failed' then FAILED
      when 'delivered' then DELIVERED
      when 'undelivered' then UNDELIVERED
      when 'receiving' then RECEIVING
      when 'received' then RECEIVED
      when 'accepted' then ACCEPTED
      when 'scheduled' then SCHEDULED
      when 'read' then READ
      when 'partially_delivered' then PARTIALLY_DELIVERED
      when 'canceled' then CANCELED
      else
        default_value
      end
    end
  end
end
