# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # VerificationAttempt Model.
  class VerificationAttempt < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID that uniquely identifies the verification attempt resource.
    # @return [String]
    attr_accessor :sid

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Verification resource.
    # @return [String]
    attr_accessor :account_sid

    # The SID of the [Service](https://www.twilio.com/docs/verify/api/service)
    # used to generate the attempt.
    # @return [String]
    attr_accessor :service_sid

    # The SID of the
    # [Verification](https://www.twilio.com/docs/verify/api/verification) that
    # generated the attempt.
    # @return [String]
    attr_accessor :verification_sid

    # The date that this Attempt was created, given in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date that this Attempt was updated, given in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # A string specifying the conversion status of the verification. A
    # conversion happens when the user is able to provide the correct code.
    # Possible values are `CONVERTED` and `UNCONVERTED`.
    # @return [VerificationAttemptEnumConversionStatus]
    attr_accessor :conversion_status

    # A string specifying the communication channel used for the verification
    # attempt.
    # @return [VerificationAttemptEnumChannels]
    attr_accessor :channel

    # An object containing the charge for this verification attempt related to
    # the channel costs and the currency used. The costs related to the
    # succeeded verifications are not included. May not be immediately
    # available. More information on pricing is available
    # [here](https://www.twilio.com/en-us/verify/pricing).
    # @return [Object]
    attr_accessor :price

    # An object containing the channel specific information for an attempt.
    # @return [Object]
    attr_accessor :channel_data

    # An object containing the channel specific information for an attempt.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['sid'] = 'sid'
      @_hash['account_sid'] = 'account_sid'
      @_hash['service_sid'] = 'service_sid'
      @_hash['verification_sid'] = 'verification_sid'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['conversion_status'] = 'conversion_status'
      @_hash['channel'] = 'channel'
      @_hash['price'] = 'price'
      @_hash['channel_data'] = 'channel_data'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        sid
        account_sid
        service_sid
        verification_sid
        date_created
        date_updated
        conversion_status
        channel
        price
        channel_data
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        sid
        account_sid
        service_sid
        verification_sid
        date_created
        date_updated
        price
        channel_data
        url
      ]
    end

    def initialize(sid: SKIP, account_sid: SKIP, service_sid: SKIP,
                   verification_sid: SKIP, date_created: SKIP,
                   date_updated: SKIP, conversion_status: SKIP, channel: SKIP,
                   price: SKIP, channel_data: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @sid = sid unless sid == SKIP
      @account_sid = account_sid unless account_sid == SKIP
      @service_sid = service_sid unless service_sid == SKIP
      @verification_sid = verification_sid unless verification_sid == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @conversion_status = conversion_status unless conversion_status == SKIP
      @channel = channel unless channel == SKIP
      @price = price unless price == SKIP
      @channel_data = channel_data unless channel_data == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      service_sid = hash.key?('service_sid') ? hash['service_sid'] : SKIP
      verification_sid =
        hash.key?('verification_sid') ? hash['verification_sid'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      conversion_status =
        hash.key?('conversion_status') ? hash['conversion_status'] : SKIP
      channel = hash.key?('channel') ? hash['channel'] : SKIP
      price = hash.key?('price') ? hash['price'] : SKIP
      channel_data = hash.key?('channel_data') ? hash['channel_data'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      VerificationAttempt.new(sid: sid,
                              account_sid: account_sid,
                              service_sid: service_sid,
                              verification_sid: verification_sid,
                              date_created: date_created,
                              date_updated: date_updated,
                              conversion_status: conversion_status,
                              channel: channel,
                              price: price,
                              channel_data: channel_data,
                              url: url,
                              additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid}, account_sid: #{@account_sid}, service_sid: #{@service_sid},"\
      " verification_sid: #{@verification_sid}, date_created: #{@date_created}, date_updated:"\
      " #{@date_updated}, conversion_status: #{@conversion_status}, channel: #{@channel}, price:"\
      " #{@price}, channel_data: #{@channel_data}, url: #{@url}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} sid: #{@sid.inspect}, account_sid: #{@account_sid.inspect}, service_sid:"\
      " #{@service_sid.inspect}, verification_sid: #{@verification_sid.inspect}, date_created:"\
      " #{@date_created.inspect}, date_updated: #{@date_updated.inspect}, conversion_status:"\
      " #{@conversion_status.inspect}, channel: #{@channel.inspect}, price: #{@price.inspect},"\
      " channel_data: #{@channel_data.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
