# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # A string specifying the communication channel used for the verification
  # attempt.
  class VerificationAttemptEnumChannels
    VERIFICATION_ATTEMPT_ENUM_CHANNELS = [
      # TODO: Write general description for SMS
      SMS = 'sms'.freeze,

      # TODO: Write general description for CALL
      CALL = 'call'.freeze,

      # TODO: Write general description for EMAIL
      EMAIL = 'email'.freeze,

      # TODO: Write general description for WHATSAPP
      WHATSAPP = 'whatsapp'.freeze,

      # TODO: Write general description for RBM
      RBM = 'rbm'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      VERIFICATION_ATTEMPT_ENUM_CHANNELS.include?(value)
    end

    def self.from_value(value, default_value = SMS)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'sms' then SMS
      when 'call' then CALL
      when 'email' then EMAIL
      when 'whatsapp' then WHATSAPP
      when 'rbm' then RBM
      else
        default_value
      end
    end
  end
end
