# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # VerificationAttemptEnumCallStatus.
  class VerificationAttemptEnumCallStatus
    VERIFICATION_ATTEMPT_ENUM_CALL_STATUS = [
      # TODO: Write general description for QUEUED
      QUEUED = 'queued'.freeze,

      # TODO: Write general description for INPROGRESS
      INPROGRESS = 'in-progress'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'completed'.freeze,

      # TODO: Write general description for BUSY
      BUSY = 'busy'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for NOANSWER
      NOANSWER = 'no-answer'.freeze,

      # TODO: Write general description for RINGING
      RINGING = 'ringing'.freeze,

      # TODO: Write general description for CANCELED
      CANCELED = 'canceled'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      VERIFICATION_ATTEMPT_ENUM_CALL_STATUS.include?(value)
    end

    def self.from_value(value, default_value = QUEUED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'queued' then QUEUED
      when 'inprogress' then INPROGRESS
      when 'completed' then COMPLETED
      when 'busy' then BUSY
      when 'failed' then FAILED
      when 'noanswer' then NOANSWER
      when 'ringing' then RINGING
      when 'canceled' then CANCELED
      else
        default_value
      end
    end
  end
end
