# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # WorkerStatistics Model.
  class WorkerStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # An object that contains the real-time statistics for the Worker.
    # @return [Object]
    attr_accessor :realtime

    # An object that contains the cumulative statistics for the Worker.
    # @return [Object]
    attr_accessor :cumulative

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Worker resource.
    # @return [String]
    attr_accessor :account_sid

    # The SID of the Workspace that contains the Worker.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the Worker statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['realtime'] = 'realtime'
      @_hash['cumulative'] = 'cumulative'
      @_hash['account_sid'] = 'account_sid'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        realtime
        cumulative
        account_sid
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        realtime
        cumulative
        account_sid
        workspace_sid
        url
      ]
    end

    def initialize(realtime: SKIP, cumulative: SKIP, account_sid: SKIP,
                   workspace_sid: SKIP, url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @realtime = realtime unless realtime == SKIP
      @cumulative = cumulative unless cumulative == SKIP
      @account_sid = account_sid unless account_sid == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      realtime = hash.key?('realtime') ? hash['realtime'] : SKIP
      cumulative = hash.key?('cumulative') ? hash['cumulative'] : SKIP
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WorkerStatistics.new(realtime: realtime,
                           cumulative: cumulative,
                           account_sid: account_sid,
                           workspace_sid: workspace_sid,
                           url: url,
                           additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} realtime: #{@realtime}, cumulative: #{@cumulative}, account_sid:"\
      " #{@account_sid}, workspace_sid: #{@workspace_sid}, url: #{@url}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} realtime: #{@realtime.inspect}, cumulative: #{@cumulative.inspect},"\
      " account_sid: #{@account_sid.inspect}, workspace_sid: #{@workspace_sid.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
