# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # WorkersRealTimeStatistics Model.
  class WorkersRealTimeStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Worker resource.
    # @return [String]
    attr_accessor :account_sid

    # The number of current Workers by Activity.
    # @return [Array[Object]]
    attr_accessor :activity_statistics

    # The total number of Workers.
    # @return [Integer]
    attr_accessor :total_workers

    # The SID of the Workspace that contains the Workers.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the Workers statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['activity_statistics'] = 'activity_statistics'
      @_hash['total_workers'] = 'total_workers'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        activity_statistics
        total_workers
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        activity_statistics
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, activity_statistics: SKIP,
                   total_workers: 0, workspace_sid: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @activity_statistics = activity_statistics unless activity_statistics == SKIP
      @total_workers = total_workers unless total_workers == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      activity_statistics =
        hash.key?('activity_statistics') ? hash['activity_statistics'] : SKIP
      total_workers = hash['total_workers'] ||= 0
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WorkersRealTimeStatistics.new(account_sid: account_sid,
                                    activity_statistics: activity_statistics,
                                    total_workers: total_workers,
                                    workspace_sid: workspace_sid,
                                    url: url,
                                    additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, activity_statistics: #{@activity_statistics},"\
      " total_workers: #{@total_workers}, workspace_sid: #{@workspace_sid}, url: #{@url},"\
      " additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, activity_statistics:"\
      " #{@activity_statistics.inspect}, total_workers: #{@total_workers.inspect}, workspace_sid:"\
      " #{@workspace_sid.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
