# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # WorkerChannel Model.
  class WorkerChannel < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Worker resource.
    # @return [String]
    attr_accessor :account_sid

    # The total number of Tasks assigned to Worker for the TaskChannel type.
    # @return [Integer]
    attr_accessor :assigned_tasks

    # Whether the Worker should receive Tasks of the TaskChannel type.
    # @return [TrueClass | FalseClass]
    attr_accessor :available

    # The current percentage of capacity the TaskChannel has available. Can be a
    # number between `0` and `100`. A value of `0` indicates that TaskChannel
    # has no capacity available and a value of `100` means the  Worker is
    # available to receive any Tasks of this TaskChannel type.
    # @return [Integer]
    attr_accessor :available_capacity_percentage

    # The current configured capacity for the WorkerChannel. TaskRouter will not
    # create any reservations after the assigned Tasks for the Worker reaches
    # the value.
    # @return [Integer]
    attr_accessor :configured_capacity

    # The date and time in GMT when the resource was created specified in [RFC
    # 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date and time in GMT when the resource was last updated specified in
    # [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # The unique string that we created to identify the WorkerChannel resource.
    # @return [String]
    attr_accessor :sid

    # The SID of the TaskChannel.
    # @return [String]
    attr_accessor :task_channel_sid

    # The unique name of the TaskChannel, such as `voice` or `sms`.
    # @return [String]
    attr_accessor :task_channel_unique_name

    # The SID of the Worker that contains the WorkerChannel.
    # @return [String]
    attr_accessor :worker_sid

    # The SID of the Workspace that contains the WorkerChannel.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the WorkerChannel resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['assigned_tasks'] = 'assigned_tasks'
      @_hash['available'] = 'available'
      @_hash['available_capacity_percentage'] =
        'available_capacity_percentage'
      @_hash['configured_capacity'] = 'configured_capacity'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['sid'] = 'sid'
      @_hash['task_channel_sid'] = 'task_channel_sid'
      @_hash['task_channel_unique_name'] = 'task_channel_unique_name'
      @_hash['worker_sid'] = 'worker_sid'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        assigned_tasks
        available
        available_capacity_percentage
        configured_capacity
        date_created
        date_updated
        sid
        task_channel_sid
        task_channel_unique_name
        worker_sid
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        available
        date_created
        date_updated
        sid
        task_channel_sid
        task_channel_unique_name
        worker_sid
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, assigned_tasks: 0, available: SKIP,
                   available_capacity_percentage: 0, configured_capacity: 0,
                   date_created: SKIP, date_updated: SKIP, sid: SKIP,
                   task_channel_sid: SKIP, task_channel_unique_name: SKIP,
                   worker_sid: SKIP, workspace_sid: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @assigned_tasks = assigned_tasks unless assigned_tasks == SKIP
      @available = available unless available == SKIP
      unless available_capacity_percentage == SKIP
        @available_capacity_percentage =
          available_capacity_percentage
      end
      @configured_capacity = configured_capacity unless configured_capacity == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @sid = sid unless sid == SKIP
      @task_channel_sid = task_channel_sid unless task_channel_sid == SKIP
      @task_channel_unique_name = task_channel_unique_name unless task_channel_unique_name == SKIP
      @worker_sid = worker_sid unless worker_sid == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      assigned_tasks = hash['assigned_tasks'] ||= 0
      available = hash.key?('available') ? hash['available'] : SKIP
      available_capacity_percentage =
        hash['available_capacity_percentage'] ||= 0
      configured_capacity = hash['configured_capacity'] ||= 0
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      task_channel_sid =
        hash.key?('task_channel_sid') ? hash['task_channel_sid'] : SKIP
      task_channel_unique_name =
        hash.key?('task_channel_unique_name') ? hash['task_channel_unique_name'] : SKIP
      worker_sid = hash.key?('worker_sid') ? hash['worker_sid'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WorkerChannel.new(account_sid: account_sid,
                        assigned_tasks: assigned_tasks,
                        available: available,
                        available_capacity_percentage: available_capacity_percentage,
                        configured_capacity: configured_capacity,
                        date_created: date_created,
                        date_updated: date_updated,
                        sid: sid,
                        task_channel_sid: task_channel_sid,
                        task_channel_unique_name: task_channel_unique_name,
                        worker_sid: worker_sid,
                        workspace_sid: workspace_sid,
                        url: url,
                        additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, assigned_tasks: #{@assigned_tasks},"\
      " available: #{@available}, available_capacity_percentage:"\
      " #{@available_capacity_percentage}, configured_capacity: #{@configured_capacity},"\
      " date_created: #{@date_created}, date_updated: #{@date_updated}, sid: #{@sid},"\
      " task_channel_sid: #{@task_channel_sid}, task_channel_unique_name:"\
      " #{@task_channel_unique_name}, worker_sid: #{@worker_sid}, workspace_sid:"\
      " #{@workspace_sid}, url: #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, assigned_tasks:"\
      " #{@assigned_tasks.inspect}, available: #{@available.inspect},"\
      " available_capacity_percentage: #{@available_capacity_percentage.inspect},"\
      " configured_capacity: #{@configured_capacity.inspect}, date_created:"\
      " #{@date_created.inspect}, date_updated: #{@date_updated.inspect}, sid: #{@sid.inspect},"\
      " task_channel_sid: #{@task_channel_sid.inspect}, task_channel_unique_name:"\
      " #{@task_channel_unique_name.inspect}, worker_sid: #{@worker_sid.inspect}, workspace_sid:"\
      " #{@workspace_sid.inspect}, url: #{@url.inspect}, additional_properties:"\
      " #{@additional_properties}>"
    end
  end
end
