# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # WorkflowRealTimeStatistics Model.
  class WorkflowRealTimeStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Workflow resource.
    # @return [String]
    attr_accessor :account_sid

    # The age of the longest waiting Task.
    # @return [Integer]
    attr_accessor :longest_task_waiting_age

    # The SID of the longest waiting Task.
    # @return [String]
    attr_accessor :longest_task_waiting_sid

    # The number of Tasks by priority. For example: `{"0": "10", "99": "5"}`
    # shows 10 Tasks at priority 0 and 5 at priority 99.
    # @return [Object]
    attr_accessor :tasks_by_priority

    # The number of Tasks by their current status. For example: `{"pending":
    # "1", "reserved": "3", "assigned": "2", "completed": "5"}`.
    # @return [Object]
    attr_accessor :tasks_by_status

    # The total number of Tasks.
    # @return [Integer]
    attr_accessor :total_tasks

    # Returns the list of Tasks that are being controlled by the Workflow with
    # the specified SID value.
    # @return [String]
    attr_accessor :workflow_sid

    # The SID of the Workspace that contains the Workflow.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the Workflow statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['longest_task_waiting_age'] = 'longest_task_waiting_age'
      @_hash['longest_task_waiting_sid'] = 'longest_task_waiting_sid'
      @_hash['tasks_by_priority'] = 'tasks_by_priority'
      @_hash['tasks_by_status'] = 'tasks_by_status'
      @_hash['total_tasks'] = 'total_tasks'
      @_hash['workflow_sid'] = 'workflow_sid'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        longest_task_waiting_age
        longest_task_waiting_sid
        tasks_by_priority
        tasks_by_status
        total_tasks
        workflow_sid
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        longest_task_waiting_sid
        tasks_by_priority
        tasks_by_status
        workflow_sid
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, longest_task_waiting_age: 0,
                   longest_task_waiting_sid: SKIP, tasks_by_priority: SKIP,
                   tasks_by_status: SKIP, total_tasks: 0, workflow_sid: SKIP,
                   workspace_sid: SKIP, url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @longest_task_waiting_age = longest_task_waiting_age unless longest_task_waiting_age == SKIP
      @longest_task_waiting_sid = longest_task_waiting_sid unless longest_task_waiting_sid == SKIP
      @tasks_by_priority = tasks_by_priority unless tasks_by_priority == SKIP
      @tasks_by_status = tasks_by_status unless tasks_by_status == SKIP
      @total_tasks = total_tasks unless total_tasks == SKIP
      @workflow_sid = workflow_sid unless workflow_sid == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      longest_task_waiting_age = hash['longest_task_waiting_age'] ||= 0
      longest_task_waiting_sid =
        hash.key?('longest_task_waiting_sid') ? hash['longest_task_waiting_sid'] : SKIP
      tasks_by_priority =
        hash.key?('tasks_by_priority') ? hash['tasks_by_priority'] : SKIP
      tasks_by_status =
        hash.key?('tasks_by_status') ? hash['tasks_by_status'] : SKIP
      total_tasks = hash['total_tasks'] ||= 0
      workflow_sid = hash.key?('workflow_sid') ? hash['workflow_sid'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WorkflowRealTimeStatistics.new(account_sid: account_sid,
                                     longest_task_waiting_age: longest_task_waiting_age,
                                     longest_task_waiting_sid: longest_task_waiting_sid,
                                     tasks_by_priority: tasks_by_priority,
                                     tasks_by_status: tasks_by_status,
                                     total_tasks: total_tasks,
                                     workflow_sid: workflow_sid,
                                     workspace_sid: workspace_sid,
                                     url: url,
                                     additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, longest_task_waiting_age:"\
      " #{@longest_task_waiting_age}, longest_task_waiting_sid: #{@longest_task_waiting_sid},"\
      " tasks_by_priority: #{@tasks_by_priority}, tasks_by_status: #{@tasks_by_status},"\
      " total_tasks: #{@total_tasks}, workflow_sid: #{@workflow_sid}, workspace_sid:"\
      " #{@workspace_sid}, url: #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, longest_task_waiting_age:"\
      " #{@longest_task_waiting_age.inspect}, longest_task_waiting_sid:"\
      " #{@longest_task_waiting_sid.inspect}, tasks_by_priority: #{@tasks_by_priority.inspect},"\
      " tasks_by_status: #{@tasks_by_status.inspect}, total_tasks: #{@total_tasks.inspect},"\
      " workflow_sid: #{@workflow_sid.inspect}, workspace_sid: #{@workspace_sid.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
