# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # Workspace Model.
  class Workspace < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Workspace resource.
    # @return [String]
    attr_accessor :account_sid

    # The date and time in GMT when the resource was created specified in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date and time in GMT when the resource was last updated specified in
    # [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # The name of the default activity.
    # @return [String]
    attr_accessor :default_activity_name

    # The SID of the Activity that will be used when new Workers are created in
    # the Workspace.
    # @return [String]
    attr_accessor :default_activity_sid

    # The URL we call when an event occurs. If provided, the Workspace will
    # publish events to this URL, for example, to collect data for reporting.
    # See [Workspace Events](https://www.twilio.com/docs/taskrouter/api/event)
    # for more information. This parameter supports Twilio's [Webhooks (HTTP
    # callbacks) Connection
    # Overrides](https://www.twilio.com/docs/usage/webhooks/webhooks-connection-
    # overrides).
    # @return [String]
    attr_accessor :event_callback_url

    # The list of Workspace events for which to call `event_callback_url`. For
    # example, if `EventsFilter=task.created, task.canceled,
    # worker.activity.update`, then TaskRouter will call event_callback_url only
    # when a task is created, canceled, or a Worker activity is updated.
    # @return [String]
    attr_accessor :events_filter

    # The string that you assigned to describe the Workspace resource. For
    # example `Customer Support` or `2014 Election Campaign`.
    # @return [String]
    attr_accessor :friendly_name

    # Whether multi-tasking is enabled. The default is `true`, which enables
    # multi-tasking. Multi-tasking allows Workers to handle multiple Tasks
    # simultaneously. When enabled (`true`), each Worker can receive parallel
    # reservations up to the per-channel maximums defined in the Workers
    # section. In single-tasking each Worker would only receive a new
    # reservation when the previous task is completed. Learn more at
    # [Multitasking](https://www.twilio.com/docs/taskrouter/multitasking).
    # @return [TrueClass | FalseClass]
    attr_accessor :multi_task_enabled

    # The unique string that we created to identify the Workspace resource.
    # @return [String]
    attr_accessor :sid

    # The name of the timeout activity.
    # @return [String]
    attr_accessor :timeout_activity_name

    # The SID of the Activity that will be assigned to a Worker when a Task
    # reservation times out without a response.
    # @return [String]
    attr_accessor :timeout_activity_sid

    # The type of TaskQueue to prioritize when Workers are receiving Tasks from
    # both types of TaskQueues. Can be: `LIFO` or `FIFO` and the default is
    # `FIFO`. For more information, see [Queue
    # Ordering](https://www.twilio.com/docs/taskrouter/queue-ordering-last-first
    # -out-lifo).
    # @return [WorkspaceQueueOrder]
    attr_accessor :prioritize_queue_order

    # The absolute URL of the Workspace resource.
    # @return [String]
    attr_accessor :url

    # The URLs of related resources.
    # @return [Object]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['date_created'] = 'date_created'
      @_hash['date_updated'] = 'date_updated'
      @_hash['default_activity_name'] = 'default_activity_name'
      @_hash['default_activity_sid'] = 'default_activity_sid'
      @_hash['event_callback_url'] = 'event_callback_url'
      @_hash['events_filter'] = 'events_filter'
      @_hash['friendly_name'] = 'friendly_name'
      @_hash['multi_task_enabled'] = 'multi_task_enabled'
      @_hash['sid'] = 'sid'
      @_hash['timeout_activity_name'] = 'timeout_activity_name'
      @_hash['timeout_activity_sid'] = 'timeout_activity_sid'
      @_hash['prioritize_queue_order'] = 'prioritize_queue_order'
      @_hash['url'] = 'url'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        date_created
        date_updated
        default_activity_name
        default_activity_sid
        event_callback_url
        events_filter
        friendly_name
        multi_task_enabled
        sid
        timeout_activity_name
        timeout_activity_sid
        prioritize_queue_order
        url
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        date_created
        date_updated
        default_activity_name
        default_activity_sid
        event_callback_url
        events_filter
        friendly_name
        multi_task_enabled
        sid
        timeout_activity_name
        timeout_activity_sid
        url
        links
      ]
    end

    def initialize(account_sid: SKIP, date_created: SKIP, date_updated: SKIP,
                   default_activity_name: SKIP, default_activity_sid: SKIP,
                   event_callback_url: SKIP, events_filter: SKIP,
                   friendly_name: SKIP, multi_task_enabled: SKIP, sid: SKIP,
                   timeout_activity_name: SKIP, timeout_activity_sid: SKIP,
                   prioritize_queue_order: SKIP, url: SKIP, links: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @default_activity_name = default_activity_name unless default_activity_name == SKIP
      @default_activity_sid = default_activity_sid unless default_activity_sid == SKIP
      @event_callback_url = event_callback_url unless event_callback_url == SKIP
      @events_filter = events_filter unless events_filter == SKIP
      @friendly_name = friendly_name unless friendly_name == SKIP
      @multi_task_enabled = multi_task_enabled unless multi_task_enabled == SKIP
      @sid = sid unless sid == SKIP
      @timeout_activity_name = timeout_activity_name unless timeout_activity_name == SKIP
      @timeout_activity_sid = timeout_activity_sid unless timeout_activity_sid == SKIP
      @prioritize_queue_order = prioritize_queue_order unless prioritize_queue_order == SKIP
      @url = url unless url == SKIP
      @links = links unless links == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      default_activity_name =
        hash.key?('default_activity_name') ? hash['default_activity_name'] : SKIP
      default_activity_sid =
        hash.key?('default_activity_sid') ? hash['default_activity_sid'] : SKIP
      event_callback_url =
        hash.key?('event_callback_url') ? hash['event_callback_url'] : SKIP
      events_filter = hash.key?('events_filter') ? hash['events_filter'] : SKIP
      friendly_name = hash.key?('friendly_name') ? hash['friendly_name'] : SKIP
      multi_task_enabled =
        hash.key?('multi_task_enabled') ? hash['multi_task_enabled'] : SKIP
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      timeout_activity_name =
        hash.key?('timeout_activity_name') ? hash['timeout_activity_name'] : SKIP
      timeout_activity_sid =
        hash.key?('timeout_activity_sid') ? hash['timeout_activity_sid'] : SKIP
      prioritize_queue_order =
        hash.key?('prioritize_queue_order') ? hash['prioritize_queue_order'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Workspace.new(account_sid: account_sid,
                    date_created: date_created,
                    date_updated: date_updated,
                    default_activity_name: default_activity_name,
                    default_activity_sid: default_activity_sid,
                    event_callback_url: event_callback_url,
                    events_filter: events_filter,
                    friendly_name: friendly_name,
                    multi_task_enabled: multi_task_enabled,
                    sid: sid,
                    timeout_activity_name: timeout_activity_name,
                    timeout_activity_sid: timeout_activity_sid,
                    prioritize_queue_order: prioritize_queue_order,
                    url: url,
                    links: links,
                    additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, date_created: #{@date_created}, date_updated:"\
      " #{@date_updated}, default_activity_name: #{@default_activity_name}, default_activity_sid:"\
      " #{@default_activity_sid}, event_callback_url: #{@event_callback_url}, events_filter:"\
      " #{@events_filter}, friendly_name: #{@friendly_name}, multi_task_enabled:"\
      " #{@multi_task_enabled}, sid: #{@sid}, timeout_activity_name: #{@timeout_activity_name},"\
      " timeout_activity_sid: #{@timeout_activity_sid}, prioritize_queue_order:"\
      " #{@prioritize_queue_order}, url: #{@url}, links: #{@links}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, date_created:"\
      " #{@date_created.inspect}, date_updated: #{@date_updated.inspect}, default_activity_name:"\
      " #{@default_activity_name.inspect}, default_activity_sid: #{@default_activity_sid.inspect},"\
      " event_callback_url: #{@event_callback_url.inspect}, events_filter:"\
      " #{@events_filter.inspect}, friendly_name: #{@friendly_name.inspect}, multi_task_enabled:"\
      " #{@multi_task_enabled.inspect}, sid: #{@sid.inspect}, timeout_activity_name:"\
      " #{@timeout_activity_name.inspect}, timeout_activity_sid: #{@timeout_activity_sid.inspect},"\
      " prioritize_queue_order: #{@prioritize_queue_order.inspect}, url: #{@url.inspect}, links:"\
      " #{@links.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
