# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # Worker Model.
  class Worker < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Worker resource.
    # @return [String]
    attr_accessor :account_sid

    # The `friendly_name` of the Worker's current Activity.
    # @return [String]
    attr_accessor :activity_name

    # The SID of the Worker's current Activity.
    # @return [String]
    attr_accessor :activity_sid

    # The JSON string that describes the Worker. For example: `{ "email":
    # "Bob@example.com", "phone": "+5095551234" }`. **Note** If this property
    # has been assigned a value, it will only be displayed in FETCH actions that
    # return a single resource. Otherwise, this property will be null, even if
    # it has a value. This data is passed to the `assignment_callback_url` when
    # TaskRouter assigns a Task to the Worker.
    # @return [String]
    attr_accessor :attributes

    # Whether the Worker is available to perform tasks.
    # @return [TrueClass | FalseClass]
    attr_accessor :available

    # The date and time in GMT when the resource was created specified in [ISO
    # 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_created

    # The date and time in GMT of the last change to the Worker's activity
    # specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # Used to calculate Workflow statistics.
    # @return [DateTime]
    attr_accessor :date_status_changed

    # The date and time in GMT when the resource was last updated specified in
    # [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :date_updated

    # The string that you assigned to describe the resource. Friendly names are
    # case insensitive, and unique within the TaskRouter Workspace.
    # @return [String]
    attr_accessor :friendly_name

    # The unique string that we created to identify the Worker resource.
    # @return [String]
    attr_accessor :sid

    # The SID of the Workspace that contains the Worker.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the Worker resource.
    # @return [String]
    attr_accessor :url

    # The URLs of related resources.
    # @return [Object]
    attr_accessor :links

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['activity_name'] = 'activity_name'
      @_hash['activity_sid'] = 'activity_sid'
      @_hash['attributes'] = 'attributes'
      @_hash['available'] = 'available'
      @_hash['date_created'] = 'date_created'
      @_hash['date_status_changed'] = 'date_status_changed'
      @_hash['date_updated'] = 'date_updated'
      @_hash['friendly_name'] = 'friendly_name'
      @_hash['sid'] = 'sid'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash['links'] = 'links'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        activity_name
        activity_sid
        attributes
        available
        date_created
        date_status_changed
        date_updated
        friendly_name
        sid
        workspace_sid
        url
        links
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        activity_name
        activity_sid
        attributes
        available
        date_created
        date_status_changed
        date_updated
        friendly_name
        sid
        workspace_sid
        url
        links
      ]
    end

    def initialize(account_sid: SKIP, activity_name: SKIP, activity_sid: SKIP,
                   attributes: SKIP, available: SKIP, date_created: SKIP,
                   date_status_changed: SKIP, date_updated: SKIP,
                   friendly_name: SKIP, sid: SKIP, workspace_sid: SKIP,
                   url: SKIP, links: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @activity_name = activity_name unless activity_name == SKIP
      @activity_sid = activity_sid unless activity_sid == SKIP
      @attributes = attributes unless attributes == SKIP
      @available = available unless available == SKIP
      @date_created = date_created unless date_created == SKIP
      @date_status_changed = date_status_changed unless date_status_changed == SKIP
      @date_updated = date_updated unless date_updated == SKIP
      @friendly_name = friendly_name unless friendly_name == SKIP
      @sid = sid unless sid == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @links = links unless links == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      activity_name = hash.key?('activity_name') ? hash['activity_name'] : SKIP
      activity_sid = hash.key?('activity_sid') ? hash['activity_sid'] : SKIP
      attributes = hash.key?('attributes') ? hash['attributes'] : SKIP
      available = hash.key?('available') ? hash['available'] : SKIP
      date_created = if hash.key?('date_created')
                       (DateTimeHelper.from_rfc3339(hash['date_created']) if hash['date_created'])
                     else
                       SKIP
                     end
      date_status_changed = if hash.key?('date_status_changed')
                              (DateTimeHelper.from_rfc3339(hash['date_status_changed']) if hash['date_status_changed'])
                            else
                              SKIP
                            end
      date_updated = if hash.key?('date_updated')
                       (DateTimeHelper.from_rfc3339(hash['date_updated']) if hash['date_updated'])
                     else
                       SKIP
                     end
      friendly_name = hash.key?('friendly_name') ? hash['friendly_name'] : SKIP
      sid = hash.key?('sid') ? hash['sid'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP
      links = hash.key?('links') ? hash['links'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      Worker.new(account_sid: account_sid,
                 activity_name: activity_name,
                 activity_sid: activity_sid,
                 attributes: attributes,
                 available: available,
                 date_created: date_created,
                 date_status_changed: date_status_changed,
                 date_updated: date_updated,
                 friendly_name: friendly_name,
                 sid: sid,
                 workspace_sid: workspace_sid,
                 url: url,
                 links: links,
                 additional_properties: additional_properties)
    end

    def to_custom_date_created
      DateTimeHelper.to_rfc3339(date_created)
    end

    def to_custom_date_status_changed
      DateTimeHelper.to_rfc3339(date_status_changed)
    end

    def to_custom_date_updated
      DateTimeHelper.to_rfc3339(date_updated)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, activity_name: #{@activity_name},"\
      " activity_sid: #{@activity_sid}, attributes: #{@attributes}, available: #{@available},"\
      " date_created: #{@date_created}, date_status_changed: #{@date_status_changed},"\
      " date_updated: #{@date_updated}, friendly_name: #{@friendly_name}, sid: #{@sid},"\
      " workspace_sid: #{@workspace_sid}, url: #{@url}, links: #{@links}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, activity_name:"\
      " #{@activity_name.inspect}, activity_sid: #{@activity_sid.inspect}, attributes:"\
      " #{@attributes.inspect}, available: #{@available.inspect}, date_created:"\
      " #{@date_created.inspect}, date_status_changed: #{@date_status_changed.inspect},"\
      " date_updated: #{@date_updated.inspect}, friendly_name: #{@friendly_name.inspect}, sid:"\
      " #{@sid.inspect}, workspace_sid: #{@workspace_sid.inspect}, url: #{@url.inspect}, links:"\
      " #{@links.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
