# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # WorkerInstanceStatistics Model.
  class WorkerInstanceStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Worker resource.
    # @return [String]
    attr_accessor :account_sid

    # An object that contains the cumulative statistics for the Worker.
    # @return [Object]
    attr_accessor :cumulative

    # The SID of the Worker that contains the WorkerChannel.
    # @return [String]
    attr_accessor :worker_sid

    # The SID of the Workspace that contains the WorkerChannel.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the WorkerChannel statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['cumulative'] = 'cumulative'
      @_hash['worker_sid'] = 'worker_sid'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        cumulative
        worker_sid
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        cumulative
        worker_sid
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, cumulative: SKIP, worker_sid: SKIP,
                   workspace_sid: SKIP, url: SKIP, additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @cumulative = cumulative unless cumulative == SKIP
      @worker_sid = worker_sid unless worker_sid == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      cumulative = hash.key?('cumulative') ? hash['cumulative'] : SKIP
      worker_sid = hash.key?('worker_sid') ? hash['worker_sid'] : SKIP
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WorkerInstanceStatistics.new(account_sid: account_sid,
                                   cumulative: cumulative,
                                   worker_sid: worker_sid,
                                   workspace_sid: workspace_sid,
                                   url: url,
                                   additional_properties: additional_properties)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, cumulative: #{@cumulative}, worker_sid:"\
      " #{@worker_sid}, workspace_sid: #{@workspace_sid}, url: #{@url}, additional_properties:"\
      " #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, cumulative: #{@cumulative.inspect},"\
      " worker_sid: #{@worker_sid.inspect}, workspace_sid: #{@workspace_sid.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
