# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

require 'date'
module TwilioApIs
  # WorkersCumulativeStatistics Model.
  class WorkersCumulativeStatistics < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that
    # created the Worker resource.
    # @return [String]
    attr_accessor :account_sid

    # The beginning of the interval during which these statistics were
    # calculated, in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :start_time

    # The end of the interval during which these statistics were calculated, in
    # [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
    # @return [DateTime]
    attr_accessor :end_time

    # The minimum, average, maximum, and total time (in seconds) that Workers
    # spent in each Activity.
    # @return [Array[Object]]
    attr_accessor :activity_durations

    # The total number of Reservations that were created.
    # @return [Integer]
    attr_accessor :reservations_created

    # The total number of Reservations that were accepted.
    # @return [Integer]
    attr_accessor :reservations_accepted

    # The total number of Reservations that were rejected.
    # @return [Integer]
    attr_accessor :reservations_rejected

    # The total number of Reservations that were timed out.
    # @return [Integer]
    attr_accessor :reservations_timed_out

    # The total number of Reservations that were canceled.
    # @return [Integer]
    attr_accessor :reservations_canceled

    # The total number of Reservations that were rescinded.
    # @return [Integer]
    attr_accessor :reservations_rescinded

    # The SID of the Workspace that contains the Workers.
    # @return [String]
    attr_accessor :workspace_sid

    # The absolute URL of the Workers statistics resource.
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['account_sid'] = 'account_sid'
      @_hash['start_time'] = 'start_time'
      @_hash['end_time'] = 'end_time'
      @_hash['activity_durations'] = 'activity_durations'
      @_hash['reservations_created'] = 'reservations_created'
      @_hash['reservations_accepted'] = 'reservations_accepted'
      @_hash['reservations_rejected'] = 'reservations_rejected'
      @_hash['reservations_timed_out'] = 'reservations_timed_out'
      @_hash['reservations_canceled'] = 'reservations_canceled'
      @_hash['reservations_rescinded'] = 'reservations_rescinded'
      @_hash['workspace_sid'] = 'workspace_sid'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        account_sid
        start_time
        end_time
        activity_durations
        reservations_created
        reservations_accepted
        reservations_rejected
        reservations_timed_out
        reservations_canceled
        reservations_rescinded
        workspace_sid
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      %w[
        account_sid
        start_time
        end_time
        activity_durations
        workspace_sid
        url
      ]
    end

    def initialize(account_sid: SKIP, start_time: SKIP, end_time: SKIP,
                   activity_durations: SKIP, reservations_created: 0,
                   reservations_accepted: 0, reservations_rejected: 0,
                   reservations_timed_out: 0, reservations_canceled: 0,
                   reservations_rescinded: 0, workspace_sid: SKIP, url: SKIP,
                   additional_properties: nil)
      # Add additional model properties to the instance
      additional_properties = {} if additional_properties.nil?

      @account_sid = account_sid unless account_sid == SKIP
      @start_time = start_time unless start_time == SKIP
      @end_time = end_time unless end_time == SKIP
      @activity_durations = activity_durations unless activity_durations == SKIP
      @reservations_created = reservations_created unless reservations_created == SKIP
      @reservations_accepted = reservations_accepted unless reservations_accepted == SKIP
      @reservations_rejected = reservations_rejected unless reservations_rejected == SKIP
      @reservations_timed_out = reservations_timed_out unless reservations_timed_out == SKIP
      @reservations_canceled = reservations_canceled unless reservations_canceled == SKIP
      @reservations_rescinded = reservations_rescinded unless reservations_rescinded == SKIP
      @workspace_sid = workspace_sid unless workspace_sid == SKIP
      @url = url unless url == SKIP
      @additional_properties = additional_properties
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      account_sid = hash.key?('account_sid') ? hash['account_sid'] : SKIP
      start_time = if hash.key?('start_time')
                     (DateTimeHelper.from_rfc3339(hash['start_time']) if hash['start_time'])
                   else
                     SKIP
                   end
      end_time = if hash.key?('end_time')
                   (DateTimeHelper.from_rfc3339(hash['end_time']) if hash['end_time'])
                 else
                   SKIP
                 end
      activity_durations =
        hash.key?('activity_durations') ? hash['activity_durations'] : SKIP
      reservations_created = hash['reservations_created'] ||= 0
      reservations_accepted = hash['reservations_accepted'] ||= 0
      reservations_rejected = hash['reservations_rejected'] ||= 0
      reservations_timed_out = hash['reservations_timed_out'] ||= 0
      reservations_canceled = hash['reservations_canceled'] ||= 0
      reservations_rescinded = hash['reservations_rescinded'] ||= 0
      workspace_sid = hash.key?('workspace_sid') ? hash['workspace_sid'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create a new hash for additional properties, removing known properties.
      new_hash = hash.reject { |k, _| names.value?(k) }

      additional_properties = APIHelper.get_additional_properties(
        new_hash, proc { |value| value }
      )

      # Create object from extracted values.
      WorkersCumulativeStatistics.new(account_sid: account_sid,
                                      start_time: start_time,
                                      end_time: end_time,
                                      activity_durations: activity_durations,
                                      reservations_created: reservations_created,
                                      reservations_accepted: reservations_accepted,
                                      reservations_rejected: reservations_rejected,
                                      reservations_timed_out: reservations_timed_out,
                                      reservations_canceled: reservations_canceled,
                                      reservations_rescinded: reservations_rescinded,
                                      workspace_sid: workspace_sid,
                                      url: url,
                                      additional_properties: additional_properties)
    end

    def to_custom_start_time
      DateTimeHelper.to_rfc3339(start_time)
    end

    def to_custom_end_time
      DateTimeHelper.to_rfc3339(end_time)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid}, start_time: #{@start_time}, end_time:"\
      " #{@end_time}, activity_durations: #{@activity_durations}, reservations_created:"\
      " #{@reservations_created}, reservations_accepted: #{@reservations_accepted},"\
      " reservations_rejected: #{@reservations_rejected}, reservations_timed_out:"\
      " #{@reservations_timed_out}, reservations_canceled: #{@reservations_canceled},"\
      " reservations_rescinded: #{@reservations_rescinded}, workspace_sid: #{@workspace_sid}, url:"\
      " #{@url}, additional_properties: #{@additional_properties}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} account_sid: #{@account_sid.inspect}, start_time: #{@start_time.inspect},"\
      " end_time: #{@end_time.inspect}, activity_durations: #{@activity_durations.inspect},"\
      " reservations_created: #{@reservations_created.inspect}, reservations_accepted:"\
      " #{@reservations_accepted.inspect}, reservations_rejected:"\
      " #{@reservations_rejected.inspect}, reservations_timed_out:"\
      " #{@reservations_timed_out.inspect}, reservations_canceled:"\
      " #{@reservations_canceled.inspect}, reservations_rescinded:"\
      " #{@reservations_rescinded.inspect}, workspace_sid: #{@workspace_sid.inspect}, url:"\
      " #{@url.inspect}, additional_properties: #{@additional_properties}>"
    end
  end
end
