# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # WorkerReservationCallStatus.
  class WorkerReservationCallStatus
    WORKER_RESERVATION_CALL_STATUS = [
      # TODO: Write general description for INITIATED
      INITIATED = 'initiated'.freeze,

      # TODO: Write general description for RINGING
      RINGING = 'ringing'.freeze,

      # TODO: Write general description for ANSWERED
      ANSWERED = 'answered'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'completed'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      WORKER_RESERVATION_CALL_STATUS.include?(value)
    end

    def self.from_value(value, default_value = INITIATED)
      return default_value if value.nil?

      str = value.to_s.strip

      case str.downcase
      when 'initiated' then INITIATED
      when 'ringing' then RINGING
      when 'answered' then ANSWERED
      when 'completed' then COMPLETED
      else
        default_value
      end
    end
  end
end
