# twilio_ap_is
#
# This file was automatically generated by APIMATIC v3.0 (
# https://www.apimatic.io ).

module TwilioApIs
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
